export interface ChangelogEntry {
  version: string;
  date: string;
  type: "major" | "minor" | "patch";
  title: string;
  description: string;
  changes: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "3.17.9",
    date: "2026-03-08",
    type: "minor",
    title: "Integración Inventario ↔ Mantenimiento",
    description: "Los mecánicos pueden agregar refacciones usadas directamente desde el tablero Kanban. El sistema descuenta stock automáticamente y actualiza el costo del mantenimiento.",
    changes: [
      "Sección 'Refacciones Utilizadas' en el detalle de cada tarea de mantenimiento",
      "Combobox buscable por nombre o SKU con alerta de stock bajo",
      "Al agregar refacción: inserta en maintenance_parts, descuenta stock vía trigger, suma costo al log",
      "Sheet lateral al hacer clic en tarjeta del Kanban con info completa y gestión de refacciones",
      "Costo total del mantenimiento se actualiza en tiempo real",
    ],
  },
  {
    version: "3.17.8",
    date: "2026-03-08",
    type: "minor",
    title: "Página de Control de Refacciones",
    description: "Nueva página de inventario de refacciones con tabla, búsqueda, filtro por categoría, alertas de stock bajo y formulario de alta/edición.",
    changes: [
      "Página InventoryPage con tabla de refacciones y acciones CRUD",
      "Badge destructive 'Reabastecer' cuando stock ≤ mínimo",
      "Formulario con validación Zod en español mexicano",
      "Sección 'Inventario' en sidebar con icono Package",
      "Schema partFormSchema centralizado en formSchemas.ts",
    ],
  },
  {
    version: "3.17.7",
    date: "2026-03-08",
    type: "minor",
    title: "Módulo de Control de Refacciones — Infraestructura",
    description: "Nuevas tablas parts_inventory y maintenance_parts con RLS, trigger de descuento automático de stock y hooks React Query para CRUD completo.",
    changes: [
      "Tabla parts_inventory con categorías, stock mínimo y costo unitario",
      "Tabla maintenance_parts como junction con maintenance_logs",
      "Trigger handle_part_usage para decrementar stock automáticamente",
      "RLS: lectura para staff, escritura para admin/administrativo/mechanic",
      "Hook usePartsInventory con CRUD completo y useMaintenanceParts",
    ],
  },
  {
    version: "3.17.6",
    date: "2026-03-07",
    type: "minor",
    title: "Alerta de Rentas Vencidas en el Panel",
    description: "Nueva alerta en el dashboard que muestra reservas confirmadas cuya fecha de fin ya pasó y no se ha registrado devolución, con acceso directo al módulo de devoluciones.",
    changes: [
      "Nueva sección 'Rentas Vencidas' en AlertsRow del dashboard",
      "Función get_dashboard_stats actualizada con campo overdue_bookings",
      "Muestra nombre del equipo, cliente y días de retraso",
      "Botón de acción navega a /returns con booking_id pre-seleccionado",
    ],
  },
  {
    version: "3.17.5",
    date: "2026-03-07",
    type: "patch",
    title: "Eliminar carta de Reservas del Calendario",
    description: "Se eliminó la carta duplicada de reservas del módulo de calendario ya que esta información está disponible en el módulo dedicado de reservas.",
    changes: [
      "Eliminada carta de 'Reservas' con filtros de estado del CalendarPage",
      "Limpieza de imports y estado no utilizados",
    ],
  },
  {
    version: "3.17.4",
    date: "2026-03-07",
    type: "patch",
    title: "Devolución anticipada abre formulario completo de devoluciones",
    description: "El botón 'Devolución Anticipada' en reservas ahora navega al módulo de devoluciones con la reserva pre-seleccionada, usando el mismo flujo de inspección completo.",
    changes: [
      "Botón 'Devolución Anticipada' navega a /returns con booking_id",
      "ReturnInspectionPage auto-abre dialog y pre-selecciona reserva desde query param",
      "Eliminado dialog inline de devolución anticipada en BookingActions",
    ],
  },
  {
    version: "3.17.3",
    date: "2026-03-07",
    type: "patch",
    title: "Fix paréntesis vacíos en contacto de reserva",
    description: "Corregido renderizado de '()' cuando el contacto del cliente está vacío en la tarjeta de reservas del calendario.",
    changes: [
      "Renderizado condicional del contacto del cliente en CalendarPage",
    ],
  },
  {
    version: "3.17.2",
    date: "2026-03-07",
    type: "patch",
    title: "UI mejorada de Gastos Operativos",
    description: "Tarjeta de total, barra de búsqueda, badges de categoría y empty state mejorado en la página de gastos.",
    changes: [
      "Tarjeta resumen 'Total de Gastos' con formatCurrency",
      "SearchBar para filtrar por descripción",
      "Badge con variante secondary para costo_venta y outline para el resto",
      "EmptyRow en lugar de EmptyState para tabla vacía con headers visibles",
    ],
  },
  {
    version: "3.17.1",
    date: "2026-03-07",
    type: "patch",
    title: "Formulario de Registro de Gastos con Validación",
    description: "Nuevo diálogo ExpenseFormDialog con react-hook-form + zod para registrar gastos con validación inline en español.",
    changes: [
      "Componente ExpenseFormDialog con validación zod y mensajes en español mexicano",
      "Schema expenseFormSchema centralizado en formSchemas.ts",
      "Errores inline bajo cada campo en lugar de toasts genéricos",
      "Categoría 'Costo de Venta (Directo)' explícita en el selector",
    ],
  },
  {
    version: "3.17.0",
    date: "2026-03-07",
    type: "minor",
    title: "Mejoras al Estado de Resultados",
    description: "Comparativo año vs año, gráfica de utilidad neta, margen bruto y exportación a PDF en el reporte de Estado de Resultados.",
    changes: [
      "Modo 'Comparativo' año vs año con variación absoluta y porcentual",
      "Gráfica de área de Utilidad Neta mensual con línea de referencia en cero",
      "Fila de Margen Bruto (%) después de Utilidad Bruta",
      "Botón de exportar a PDF con encabezado de empresa y formato contable",
    ],
  },
  {
    version: "3.16.2",
    date: "2026-03-07",
    type: "patch",
    title: "Filtro por año en Estado de Resultados",
    description: "Selector de año en el reporte de Estado de Resultados para separar datos por período anual.",
    changes: [
      "Selector de año (Todos / 2025 / 2026 / etc.) en el encabezado del reporte",
      "KPIs, gráfica, tabla y CSV se filtran según el año seleccionado",
      "Años disponibles se detectan dinámicamente de los datos",
    ],
  },
  {
    version: "3.16.1",
    date: "2026-03-07",
    type: "patch",
    title: "Mejora y estandarización de tablas",
    description: "Tablas mejoradas con filas zebra, encabezados sticky, bordes definidos y densidad compacta en toda la app.",
    changes: [
      "Filas zebra con fondo alternado para mejor legibilidad",
      "Encabezados sticky que permanecen fijos al hacer scroll",
      "Bordes y separadores mejorados con fondo en header",
      "Densidad compacta: padding reducido para mostrar más datos",
      "Encabezados en mayúsculas con tracking amplio para jerarquía visual",
    ],
  },
  {
    version: "3.16.0",
    date: "2026-03-07",
    type: "minor",
    title: "Costo de Venta de Montacargas",
    description: "Campo de costo de adquisición en montacargas y generación automática de gasto operativo al vender un equipo.",
    changes: [
      "Nuevo campo 'Costo de Adquisición' en formulario y detalle de montacargas",
      "Nueva categoría de gasto 'Costo de Venta' en gastos operativos",
      "Al cambiar status a 'Vendido', se genera automáticamente un gasto con el costo de adquisición",
      "Estado de Resultados incluye '(-) Costo de Venta' como costo directo antes de Utilidad Bruta",
    ],
  },
  {
    version: "3.15.2",
    date: "2026-03-07",
    type: "patch",
    title: "Estado de Resultados en formato vertical",
    description: "Tabla del Estado de Resultados transpuesta al formato contable tradicional: conceptos como filas y meses como columnas.",
    changes: [
      "Tabla transpuesta: conceptos financieros de arriba a abajo, meses de izquierda a derecha",
      "Filas de subtotal (Utilidad Bruta, Utilidad Neta) con estilo diferenciado",
      "Costos con prefijo (-) y color rojo para fácil identificación",
      "Columna sticky de conceptos para scroll horizontal",
    ],
  },
  {
    version: "3.15.1",
    date: "2026-03-07",
    type: "patch",
    title: "Estado de Resultados mejorado",
    description: "Reporte de Estado de Resultados con KPIs, gráfica de barras apiladas por categoría de gasto, utilidad bruta y total de egresos.",
    changes: [
      "4 tarjetas KPI: Ingresos, Total Egresos, Utilidad Neta, Margen Neto con colores condicionales",
      "Gráfica de barras apiladas desglosando costos por categoría (mantenimiento, daños, renta, nómina, etc.)",
      "Columna de Utilidad Bruta separando costos directos de gastos operativos",
      "Columna de Total Egresos explícita",
      "Todas las categorías de gastos siempre visibles para consistencia",
    ],
  },
  {
    version: "3.15.0",
    date: "2026-03-07",
    type: "minor",
    title: "Gastos Recurrentes",
    description: "Permite marcar gastos operativos como recurrentes mensuales y generarlos automáticamente con un solo clic.",
    changes: [
      "Switch 'Gasto recurrente mensual' en el formulario de crear/editar gastos",
      "Badge visual 'Mensual' en la tabla para identificar gastos recurrentes",
      "Botón 'Generar Recurrentes' que crea automáticamente los gastos del mes actual evitando duplicados",
      "Nueva columna 'is_recurring' en la base de datos",
    ],
  },
  {
    version: "3.14.1",
    date: "2026-03-07",
    type: "patch",
    title: "Prefijo $ en campo de monto de gastos",
    description: "Se agrega el símbolo de peso mexicano ($) como prefijo visual en el campo de monto del diálogo de gastos operativos.",
    changes: [
      "Prefijo '$' visible en el campo de monto del formulario de gastos",
      "Placeholder actualizado a '0.00' con formato mexicano",
    ],
  },
  {
    version: "3.14.0",
    date: "2026-03-07",
    type: "minor",
    title: "Módulo de Gastos Operativos y Estado de Resultados mejorado",
    description: "Nueva tabla y página CRUD para registrar gastos operativos (renta, nómina, software, depreciación, otros). El Estado de Resultados ahora incluye todas las categorías de gastos para calcular utilidad neta.",
    changes: [
      "Nueva página 'Gastos Operativos' con formulario para registrar, editar y eliminar gastos",
      "Categorías de gasto: Renta, Nómina, Software, Depreciación, Otro",
      "Filtro por categoría en la lista de gastos",
      "Estado de Resultados actualizado: muestra columnas dinámicas por cada categoría de gasto con datos",
      "Cálculo de Utilidad Neta = Ingresos - Mantenimiento - Daños - Gastos Operativos",
      "Entrada en sidebar bajo Administración con acceso para admin, administrativo y auditor",
      "Exportación CSV del Estado de Resultados incluye todas las categorías",
    ],
  },
  {
    version: "3.13.0",
    date: "2026-03-07",
    type: "minor",
    title: "Reporte Estado de Resultados mensual",
    description: "Nuevo reporte financiero que muestra ingresos (sin IVA), costos de mantenimiento, costos de daños, utilidad bruta y margen por mes.",
    changes: [
      "Nuevo reporte 'Estado de Resultados' en la sección de Reportes",
      "Tabla mensual con ingresos, costos de mantenimiento, costos de daños, utilidad bruta y margen %",
      "Gráfica de barras comparando ingresos vs costos por mes",
      "Fila de totales acumulados",
      "Exportación a CSV",
    ],
  },
  {
    version: "3.12.2",
    date: "2026-03-07",
    type: "patch",
    title: "Badge de fotos en tabla de daños",
    description: "Cada fila de daño muestra un contador de fotos para identificar rápidamente cuáles tienen evidencia fotográfica.",
    changes: [
      "Badge con ícono de cámara y conteo de fotos en cada fila de la tabla de daños",
      "Visible tanto en vista de escritorio como en tarjetas móviles",
      "Consulta optimizada que obtiene los conteos en una sola petición",
    ],
  },
  {
    version: "3.12.1",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos integradas en reporte de daño",
    description: "Ahora puedes adjuntar fotos directamente al reportar un daño manual, sin necesidad de crear el registro primero.",
    changes: [
      "Zona de drag-and-drop para fotos dentro del diálogo 'Reportar Daño'",
      "Previews locales antes de subir, con opción de eliminar",
      "Las fotos se suben automáticamente al crear el registro de daño",
    ],
  },
  {
    version: "3.12.0",
    date: "2026-03-07",
    type: "minor",
    title: "Reporte manual de daños",
    description: "Los operadores ahora pueden reportar daños encontrados en almacén sin necesidad de una inspección de devolución.",
    changes: [
      "Nuevo diálogo 'Reportar Daño' en la página de Seguimiento de Daños",
      "Selección de montacargas de todo el inventario, cliente opcional, descripción y costo estimado",
      "Disponible para roles admin, administrativo, despachador y mecánico",
    ],
  },
  {
    version: "3.11.2",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos por registro de daño en seguimiento",
    description: "Cada registro de daño ahora tiene su propia sección expandible de fotos con carga drag-and-drop y galería lightbox.",
    changes: [
      "Filas expandibles en DamageTrackingPage: clic en una fila revela la sección de fotos de ese daño",
      "Soporte completo en móvil con toggle para ver/subir fotos por daño",
      "Cada registro usa su ID como entidad para almacenar fotos independientes",
    ],
  },
  {
    version: "3.11.1",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos en inspección de devolución",
    description: "Se agregó el componente de carga de fotos drag-and-drop al formulario de inspección de devolución.",
    changes: [
      "DragDropImageUploader integrado en el diálogo de nueva inspección de devolución",
      "Permite capturar fotos del estado del equipo durante la inspección desde móvil o escritorio",
    ],
  },
  {
    version: "3.11.0",
    date: "2026-03-07",
    type: "minor",
    title: "Fotos de daño con drag-and-drop y galería lightbox",
    description: "Nuevo sistema de captura de fotos con arrastrar y soltar, cámara móvil y galería de imágenes a pantalla completa con navegación táctil.",
    changes: [
      "Nuevo componente DragDropImageUploader con react-dropzone: drag-and-drop, previsualización y captura de cámara en móvil",
      "Nuevo componente ImageGalleryLightbox con navegación por teclado, swipe táctil, zoom y tira de miniaturas",
      "Sección DamagePhotosSection integrada en ForkliftDetail para ver y subir fotos de daño",
      "Componente reutilizable para cualquier entidad que necesite gestión de fotos",
    ],
  },
  {
    version: "3.10.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tablero Kanban para mantenimiento",
    description: "Vista de tablero drag-and-drop para gestionar el estado de trabajo de los registros de mantenimiento con 4 columnas.",
    changes: [
      "Nueva vista Kanban en la página de mantenimiento con columnas: Pendiente, En Progreso, Esperando Refacciones y Completado",
      "Drag-and-drop entre columnas actualiza el estado de trabajo en la base de datos con actualización optimista",
      "Toggle para alternar entre vista de lista y vista de tablero",
      "Nueva columna work_status en maintenance_logs con valor por defecto 'pending'",
      "Componente MaintenanceKanban reutilizable con @hello-pangea/dnd",
    ],
  },
  {
    version: "3.9.0",
    date: "2026-03-07",
    type: "minor",
    title: "Firma electrónica en entregas y skeleton de carga en listas",
    description: "Nuevo componente de firma digital para completar entregas, y eliminación de layout shift en todas las páginas de lista con skeletons alineados a columnas.",
    changes: [
      "Nuevo componente SignaturePad con canvas táctil, deshacer y limpiar",
      "Diálogo de firma del cliente al marcar una entrega como completada",
      "Opción de omitir firma para completar sin captura",
      "Firma guardada como base64 en columna signature_base64 de deliveries",
      "Skeleton de carga alineado a columnas en BookingsPage (7 cols), Fleet (8 cols), InvoicesPage (7), ContractsPage (7), QuotesPage (7) y CustomersPage (6)",
      "Componente TableSkeleton mejorado con prop columnCount para renderizar tabla con celdas skeleton",
      "ListPageLayout acepta skeletonColumns para eliminar layout shift durante carga",
    ],
  },
  {
    version: "3.8.0",
    date: "2026-03-07",
    type: "minor",
    title: "Empty states, loading states y localización MXN",
    description: "Mejoras de UX en formularios, estados vacíos rediseñados y correcciones de localización en moneda y fechas.",
    changes: [
      "Nuevo componente EmptyState con icono, título, subtítulo y botón de acción",
      "Empty states aplicados automáticamente en Reservas, Flota y Facturas vía ListPageLayout",
      "Spinner de carga y texto 'Guardando…' en botones de envío de Reservas, Facturas y Contratos",
      "ContractForm migrado al componente compartido FormActions",
      "Botón Cancelar deshabilitado durante envío para prevenir navegación accidental",
    ],
  },
  {
    version: "3.7.0",
    date: "2026-03-07",
    type: "minor",
    title: "Localización completa a pesos mexicanos y español",
    description: "Correcciones de formato de moneda y fechas para garantizar consistencia en toda la aplicación.",
    changes: [
      "Meses en español (Ene, Feb…) en reporte de Ingresos vía locale es de date-fns",
      "Contratos PDF usan formatCurrency en lugar de .toFixed(2) para tarifas y depósito",
      "Eliminada función duplicada fmtMXN en pdfHelpers.ts, reemplazada por formatCurrency centralizado",
      "Limpieza de imports no usados en QuotePDFButton e InvoicePDFButton",
      "Spinner de carga con marca 'Cargando LiftGo…' en App.tsx",
    ],
  },
  {
    version: "3.6.2",
    date: "2026-03-05",
    type: "patch",
    title: "Admins pueden editar facturas en cualquier estado",
    description: "Los usuarios con rol admin ahora pueden editar facturas independientemente de su estado (enviada, vencida, pagada, parcial).",
    changes: [
      "Botón 'Editar' visible para admins en todos los estados de factura",
      "Usuarios no-admin mantienen la restricción de solo editar borradores",
    ],
  },
  {
    version: "3.6.1",
    date: "2026-03-04",
    type: "patch",
    title: "Corrección de selector de montacargas",
    description: "El selector de montacargas ahora muestra fabricante y modelo en lugar del ID interno.",
    changes: [
      "Formato cambiado de '{ID} — {modelo}' a '{fabricante} {modelo} — {ID}' en selectores",
      "Corrección aplicada en selector simple y multi-selector de cotizaciones",
    ],
  },
  {
    version: "3.6.0",
    date: "2026-03-04",
    type: "minor",
    title: "Refactorización de código",
    description: "Reorganización y limpieza del código para mejorar mantenibilidad, reducir duplicación y facilitar futuras extensiones.",
    changes: [
      "Helpers PDF reutilizables en pdfHelpers.ts (header, tabla de partidas, totales, notas)",
      "Nuevo hook useListPage que combina useSort + usePagination + useIsMobile",
      "ContractPDFButton dividido en 3 archivos: datos, generador y componente UI",
      "Consolidación de 11 useState en InvoiceForm a un solo useFormState",
      "NotesCard con modo readOnly para páginas de detalle",
      "Renombrado de variables ambiguas (qc→queryClient, fl→forklift, etc.)",
    ],
  },
  {
    version: "3.5.3",
    date: "2026-02-28",
    type: "patch",
    title: "Corrección de facturación recurrente",
    description: "La primera factura recurrente ahora cubre correctamente el mes de inicio de la reserva.",
    changes: [
      "Primera factura ahora cubre el mes de inicio de la reserva en lugar de saltarlo",
      "Corrección en la lógica de last_billed_date para facturación automática",
    ],
  },
  {
    version: "3.5.2",
    date: "2026-02-28",
    type: "patch",
    title: "Corrección de cálculo de meses en rentas",
    description: "La fecha final ahora se trata como inclusiva para calcular correctamente la duración de periodos de renta.",
    changes: [
      "Fecha final tratada como inclusiva: periodos como 01/12 al 30/11 ahora calculan 12 meses exactos",
      "Ajuste en invoiceUtils para evitar cobros de un mes menos en rentas largas",
    ],
  },
  {
    version: "3.5.1",
    date: "2026-02-27",
    type: "patch",
    title: "Revertir acciones desde la Bitácora",
    description: "Al eliminar un registro de la bitácora, ahora puedes elegir entre solo borrar el registro o revertir la acción original en la base de datos.",
    changes: [
      "Nuevo diálogo con dos opciones: borrar solo de bitácora o revertir la acción",
      "Reversión atómica: INSERT se elimina, UPDATE restaura valores anteriores, DELETE re-inserta",
      "Validación de seguridad: solo admins con whitelist de tablas permitidas",
      "Información contextual sobre qué pasará al revertir cada tipo de acción",
    ],
  },
  {
    version: "3.5.0",
    date: "2026-02-27",
    type: "minor",
    title: "Eliminar registros de la Bitácora de Cambios",
    description: "Los administradores ahora pueden eliminar registros individuales de la bitácora de cambios (audit trail) con un diálogo de confirmación.",
    changes: [
      "Nuevo botón de eliminar en cada registro de la bitácora (solo visible para Admin)",
      "Diálogo de confirmación antes de borrar para evitar eliminaciones accidentales",
      "Notificación de éxito o error al eliminar un registro",
    ],
  },
  {
    version: "3.4.0",
    date: "2026-02-27",
    type: "minor",
    title: "Reporte de Utilización por Modelo",
    description: "Nuevo reporte que agrupa la utilización de la flota por modelo de equipo, facilitando decisiones de compra al identificar qué modelos tienen alta demanda.",
    changes: [
      "Nuevo reporte 'Utilización por Modelo' en la página de Reportes",
      "Gráfica de barras horizontales con colores por nivel de utilización (verde/amarillo/rojo)",
      "Tabla detallada con unidades, disponibles, rentados, días reservados y % de utilización",
      "Exportación a CSV del reporte",
      "Equipos vendidos o retirados se excluyen automáticamente del cálculo",
    ],
  },
  {
    version: "3.3.1",
    date: "2026-02-27",
    type: "patch",
    title: "Generación de manual restringida a Admin",
    description: "Solo el rol Admin puede generar nuevos manuales. Cada regeneración incrementa automáticamente la versión y se conservan las versiones anteriores.",
    changes: [
      "Solo el rol Admin puede generar y regenerar el manual de usuario",
      "Versión incremental automática (1.0 → 2.0 → 3.0) en cada generación",
      "Se conservan versiones anteriores del manual con selector de versión",
      "Política RLS actualizada para restringir escritura solo a admin",
    ],
  },
  {
    version: "3.3.0",
    date: "2026-02-26",
    type: "minor",
    title: "Manual de Usuario con IA",
    description: "Nueva sección de Ayuda con un manual de usuario completo generado por inteligencia artificial, con documentación detallada de cada módulo y workflows paso a paso.",
    changes: [
      "Nueva página /help con manual de usuario generado por IA",
      "18 secciones cubriendo todos los módulos de la app",
      "Workflows completos: flujo de renta, facturación recurrente, daños y mantenimiento",
      "Barra de búsqueda para filtrar contenido del manual",
      "Botón de regenerar manual disponible para administradores",
      "Accesible desde el sidebar para todos los roles",
    ],
  },
  {
    version: "3.2.0",
    date: "2026-02-26",
    type: "minor",
    title: "Editor de Plantilla de Contrato",
    description: "Los administradores ahora pueden editar el contenido de contratos, checklist y pagaré desde Configuración de Operaciones, sin modificar código.",
    changes: [
      "Nueva pestaña 'Plantilla de Contrato' en Configuración de Operaciones",
      "Editor de párrafo introductorio, declaraciones, cláusulas, checklist y pagaré",
      "Sistema de placeholders dinámicos ({arrendador}, {tarifa_mensual}, etc.)",
      "Generación de PDF lee la plantilla de la base de datos con fallback al contenido original",
      "Guía visual de placeholders disponibles en la interfaz de edición",
    ],
  },
  {
    version: "3.1.0",
    date: "2026-02-26",
    type: "minor",
    title: "Página de Changelog",
    description: "Nueva página dentro de la app que muestra el historial completo de cambios organizados por versión semántica.",
    changes: [
      "Historial de cambios con versionado semántico (MAJOR.MINOR.PATCH)",
      "Línea de tiempo visual con badges de color por tipo de cambio",
      "Filtros por tipo: Mayor, Menor y Parche",
      "Accesible desde el sidebar para todos los roles",
    ],
  },
  {
    version: "3.0.1",
    date: "2026-02-26",
    type: "patch",
    title: "Representante legal en clientes",
    description: "Se agregó el campo de representante legal en la ficha del cliente, y se integró automáticamente en el contrato y el pagaré.",
    changes: [
      "Nuevo campo 'Representante Legal' en el formulario de clientes",
      "El nombre del representante aparece automáticamente en el contrato PDF",
      "El pagaré (Anexo B) incluye al representante legal como firmante",
    ],
  },
  {
    version: "3.0.0",
    date: "2026-02-25",
    type: "major",
    title: "Contratos profesionales con anexos legales",
    description: "Rediseño completo del módulo de contratos con un machote profesional que incluye cláusulas legales, checklist de entrega y pagaré.",
    changes: [
      "8 cláusulas legales profesionales (objeto, vigencia, renta, obligaciones, etc.)",
      "Anexo A: Checklist de condiciones del equipo al momento de entrega",
      "Anexo B: Pagaré con datos del cliente y montos del contrato",
      "PDF multi-página generado con jsPDF",
      "Plantillas de contrato editables desde Configuración",
      "Testigos configurables por contrato",
    ],
  },
  {
    version: "2.5.1",
    date: "2026-02-24",
    type: "patch",
    title: "Actividad en español",
    description: "El feed de actividad ahora muestra todos los eventos traducidos al español en lugar de inglés.",
    changes: [
      "Traducciones completas del feed de actividad al español",
      "Tipos de evento y descripciones en lenguaje natural",
    ],
  },
  {
    version: "2.5.0",
    date: "2026-02-24",
    type: "minor",
    title: "Rol de auditor",
    description: "Nuevo rol 'auditor' que permite ver toda la información del sistema sin poder modificar nada.",
    changes: [
      "Rol 'auditor' con acceso de solo lectura a todas las secciones",
      "Visible en la gestión de usuarios para asignar a nuevos miembros",
    ],
  },
  {
    version: "2.4.1",
    date: "2026-02-23",
    type: "patch",
    title: "Corrección de permisos de perfil",
    description: "Se corrigió un problema donde los clientes del portal podían ver información de perfiles internos.",
    changes: [
      "Separación de permisos entre perfiles de clientes y personal interno",
      "Los clientes solo ven su propia información",
    ],
  },
  {
    version: "2.4.0",
    date: "2026-02-23",
    type: "minor",
    title: "Rol administrativo",
    description: "Nuevo rol 'administrativo' con permisos completos de operación, similar al dispatcher pero con acceso a configuración.",
    changes: [
      "Rol 'administrativo' con acceso completo a operaciones",
      "Acceso a configuración de empresa y operaciones",
      "Puede gestionar reservas, contratos, facturas y entregas",
    ],
  },
  {
    version: "2.3.1",
    date: "2026-02-23",
    type: "patch",
    title: "Mejoras al dashboard",
    description: "El panel principal ahora muestra información más precisa sobre la flota y su utilización.",
    changes: [
      "Nuevo estado 'vendido' para equipos retirados de la flota activa",
      "Gráfica de utilización semanal en el dashboard",
      "Los equipos retirados ya no se cuentan en las estadísticas de flota",
    ],
  },
  {
    version: "2.3.0",
    date: "2026-02-23",
    type: "minor",
    title: "Portal de clientes",
    description: "Los clientes ahora pueden iniciar sesión en su propio portal para ver sus rentas, facturas y contratos.",
    changes: [
      "Nuevo rol 'customer' para clientes con cuenta",
      "Pantalla de login dedicada para clientes en /portal/login",
      "Dashboard del portal con resumen de cuenta",
      "Vista de facturas y contratos desde la perspectiva del cliente",
      "Invitación de clientes por correo electrónico",
    ],
  },
  {
    version: "2.2.0",
    date: "2026-02-15",
    type: "minor",
    title: "Contratos, pagos y auditoría",
    description: "Se agregaron contratos de renta, registro de pagos parciales/totales, y auditoría detallada de cambios.",
    changes: [
      "Módulo de contratos con número consecutivo automático",
      "Registro de pagos con método, referencia y notas",
      "Auditoría detallada que registra qué campos cambiaron y sus valores anteriores",
      "Estado de factura se actualiza automáticamente al registrar pagos",
    ],
  },
  {
    version: "2.1.0",
    date: "2026-02-15",
    type: "minor",
    title: "Choferes, mecánicos y datos fiscales",
    description: "Nuevos catálogos de choferes y mecánicos, más integración con datos fiscales del SAT para facturación.",
    changes: [
      "Catálogo de choferes con licencia y datos de contacto",
      "Catálogo de mecánicos con especialización",
      "Configuración de datos fiscales de la empresa (RFC, razón social, régimen)",
      "Campos de CFDI en facturas (uso CFDI, forma de pago, método de pago)",
    ],
  },
  {
    version: "2.0.3",
    date: "2026-02-15",
    type: "patch",
    title: "Cancelación de reservas y validaciones",
    description: "Ahora se pueden cancelar reservas activas, y se validó que no haya equipos con nombres o series duplicadas.",
    changes: [
      "Botón de cancelar reserva con confirmación",
      "Validación de nombres únicos en equipos",
      "Validación de números de serie únicos",
    ],
  },
  {
    version: "2.0.2",
    date: "2026-02-14",
    type: "patch",
    title: "Optimización de base de datos",
    description: "Se agregaron índices en las tablas principales para mejorar la velocidad de las consultas.",
    changes: [
      "Índices de rendimiento en reservas, facturas, mantenimiento y más",
      "Mejora en tiempos de carga de listados grandes",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-02-14",
    type: "patch",
    title: "Procedimientos atómicos",
    description: "Las operaciones críticas ahora se ejecutan como transacciones atómicas para evitar datos inconsistentes.",
    changes: [
      "Crear reserva: valida disponibilidad y cambia estado del equipo en una sola transacción",
      "Eliminar equipo: limpia dependencias automáticamente",
      "Completar inspección: cierra reserva y libera equipo de forma atómica",
    ],
  },
  {
    version: "2.0.0",
    date: "2026-02-14",
    type: "major",
    title: "Autenticación, roles y nuevos módulos",
    description: "Gran actualización que agrega sistema de usuarios con roles, cotizaciones, actividad y registro de daños.",
    changes: [
      "Sistema de autenticación con login y registro",
      "Roles de usuario: admin, dispatcher, mecánico",
      "Control de acceso por rol en todas las secciones",
      "Módulo de cotizaciones con número consecutivo",
      "Feed de actividad en tiempo real",
      "Registro de daños vinculado a equipos y reservas",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-02-13",
    type: "minor",
    title: "Devoluciones, entregas y documentos",
    description: "Se completó el flujo operativo con inspecciones de devolución, programación de entregas y adjuntos.",
    changes: [
      "Inspecciones de devolución con checklist de condición",
      "Programación de entregas y recolecciones",
      "Documentos adjuntos en reservas, equipos y clientes",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-02-13",
    type: "minor",
    title: "Clientes, mantenimiento y facturas",
    description: "Se agregaron los módulos de clientes, registro de mantenimiento, facturación y catálogo de modelos.",
    changes: [
      "Catálogo de clientes con datos de contacto",
      "Registro de mantenimiento por equipo",
      "Módulo de facturación con partidas y totales",
      "Catálogo de modelos de equipo con especificaciones por defecto",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-02-12",
    type: "major",
    title: "Lanzamiento inicial",
    description: "Primera versión del sistema con los módulos básicos para gestionar una flota de montacargas en renta.",
    changes: [
      "Catálogo de equipos (montacargas) con estado y especificaciones",
      "Reservas con fechas de inicio y fin",
      "Calendario visual de disponibilidad",
      "Panel principal con estadísticas generales",
    ],
  },
];

export const CURRENT_VERSION = changelog[0].version;
