export interface ChangelogEntry {
  version: string;
  date: string;
  type: "major" | "minor" | "patch";
  title: string;
  description: string;
  changes: string[];
}

export const changelog: ChangelogEntry[] = [
  {
    version: "3.38.3",
    date: "2026-03-12",
    type: "patch",
    title: "Sincronización automática de costo de venta",
    description: "Al modificar el costo de adquisición de un equipo vendido, se actualiza automáticamente el gasto de costo de venta correspondiente en gastos operativos.",
    changes: [
      "Sincronización automática entre costo de adquisición y gasto de costo de venta",
      "Invalidación de caché de gastos operativos al actualizar equipo",
    ],
  },
  {
    version: "3.38.2",
    date: "2026-03-12",
    type: "patch",
    title: "Filtrado de categorías en gastos",
    description: "Se eliminan las categorías 'Software' y 'Depreciación' del dropdown al registrar un nuevo gasto operativo para simplificar el catálogo visible.",
    changes: [
      "Categorías 'software' y 'depreciacion' excluidas del selector de categorías",
      "Categorías visibles: Renta, Nómina, Costo de Venta, Otro",
    ],
  },
  {
    version: "3.38.1",
    date: "2026-03-12",
    type: "patch",
    title: "Limpieza visual del Estado de Resultados",
    description: "Se elimina la gráfica de barras y se reacomodan los controles de año, CSV y PDF en una barra independiente entre los KPIs y la tabla.",
    changes: [
      "Eliminación de la gráfica BarChart del Estado de Resultados",
      "Barra de controles (año, CSV, PDF) reubicada entre KPIs y tabla",
      "Limpieza de imports y código muerto de recharts",
    ],
  },
  {
    version: "3.38.0",
    date: "2026-03-12",
    type: "minor",
    title: "Toggle base contable en Estado de Resultados",
    description: "Se agrega un switch para alternar entre base devengada (por fecha de emisión) y flujo de efectivo (por fecha de cobro) en el reporte de Estado de Resultados.",
    changes: [
      "Toggle Devengado / Flujo de efectivo en la página de Estado de Resultados",
      "Filtrado condicional de facturas según la base contable seleccionada",
    ],
  },
  {
    version: "3.37.1",
    date: "2026-03-12",
    type: "patch",
    title: "Simplificación de Estado de Resultados",
    description: "Se remueve la gráfica de Utilidad Neta Mensual del reporte para mantener el enfoque en la tabla de datos y reducir la complejidad visual.",
    changes: [
      "Eliminación de la gráfica de área de Utilidad Neta Mensual",
      "Limpieza de imports y variables no utilizadas",
    ],
  },
  {
    version: "3.37.0",
    date: "2026-03-12",
    type: "minor",
    title: "Ingresos en base devengada",
    description: "El Estado de Resultados ahora registra ingresos por fecha de emisión (issued_at) en lugar de fecha de cobro, incluyendo facturas emitidas, pagadas y vencidas.",
    changes: [
      "Cambio de base contable de flujo de efectivo a devengado",
      "Inclusión de facturas con status sent, paid y overdue",
      "Exclusión solo de borradores y canceladas",
    ],
  },
  {
    version: "3.36.1",
    date: "2026-03-12",
    type: "patch",
    title: "Alerta de equipos sin costo de adquisición",
    description: "Se muestra una alerta en el Estado de Resultados cuando existen equipos rentados sin costo de adquisición registrado, evitando omisiones en el cálculo de depreciación.",
    changes: [
      "Alerta visible con los nombres de equipos afectados",
      "Detección automática de montacargas rentados sin costo registrado",
    ],
  },
  {
    version: "3.36.0",
    date: "2026-03-12",
    type: "minor",
    title: "Desglose de depreciación por equipo",
    description: "El Estado de Resultados ahora permite expandir la fila de depreciación para ver el detalle por montacargas.",
    changes: [
      "Fila de depreciación expandible con chevron para mostrar/ocultar desglose",
      "Detalle por equipo mostrando monto mensual y total",
      "Solo se muestran equipos con rentas activas en cada mes",
    ],
  },
  {
    version: "3.35.0",
    date: "2026-03-12",
    type: "minor",
    title: "Desglose de ingresos: Rentas vs Ventas",
    description: "El Estado de Resultados ahora distingue entre ingresos por rentas y ventas de equipo.",
    changes: [
      "Ingresos separados en 'Ingresos por Rentas' e 'Ingresos por Ventas' con subtotal",
      "Gráfico de barras actualizado con barras apiladas para ambos tipos de ingreso",
      "Comparativo YoY incluye el desglose de ingresos",
    ],
  },
  {
    version: "3.34.2",
    date: "2026-03-12",
    type: "patch",
    title: "Corregir fechas de costo de venta",
    description: "Se actualizaron las fechas de los registros de costo de venta para usar la fecha de factura correspondiente en lugar de la fecha de creación del registro.",
    changes: [
      "Corregida fecha de costo de venta para 5 equipos vendidos",
      "Las fechas ahora coinciden con la fecha de emisión de la factura de venta",
    ],
  },
  {
    version: "3.34.1",
    date: "2026-03-12",
    type: "patch",
    title: "Fix costo de venta en estado de resultados",
    description: "Se corrigió que el costo de venta no aparecía en el estado de resultados al vender un montacargas.",
    changes: [
      "Backfill de registros de costo de venta faltantes para equipos vendidos",
      "Manejo de errores al crear gasto automático de costo de venta",
    ],
  },
  {
    version: "3.34.0",
    date: "2026-03-12",
    type: "minor",
    title: "Persistencia de filtros al regresar desde detalle",
    description: "Los filtros de búsqueda y estado en las listas se preservan al navegar a una página de detalle y regresar.",
    changes: [
      "Filtros de lista se guardan en sessionStorage al cambiar",
      "Botón atrás restaura filtros previos automáticamente",
    ],
  },
  {
    version: "3.33.3",
    date: "2026-03-12",
    type: "patch",
    title: "Botón atrás navega a lista correcta",
    description: "El botón de regreso en páginas de detalle ahora siempre navega a la lista correspondiente en lugar de usar el historial del navegador.",
    changes: [
      "Botón atrás usa ruta fija (backTo) en vez de navigate(-1)",
      "Comportamiento consistente en todas las páginas de detalle",
    ],
  },
  {
    version: "3.33.2",
    date: "2026-03-12",
    type: "patch",
    title: "Imagen Open Graph personalizada",
    description: "Se generó una imagen OG profesional con la marca LiftGo para redes sociales.",
    changes: [
      "Imagen OG 1200×630 con logo, montacargas y subtítulo",
      "Meta tags de OG e imagen Twitter actualizados",
    ],
  },
  {
    version: "3.33.2",
    date: "2026-03-12",
    type: "patch",
    title: "Favicon y meta tags de LiftGo",
    description: "Se agregó el favicon con el ícono LG y se actualizaron los meta tags de título y descripción del sitio.",
    changes: [
      "Favicon personalizado con las iniciales LG en naranja",
      "Título del sitio actualizado a 'LiftGo — Gestión de Montacargas'",
      "Meta descripción y Open Graph tags actualizados",
    ],
  },
  {
    version: "3.33.0",
    date: "2026-03-12",
    type: "minor",
    title: "Página dedicada de Permisos por Rol",
    description: "Nueva página /users/permissions con la matriz completa de roles vs módulos, accesible desde Gestión de Usuarios.",
    changes: [
      "Nueva página de Permisos por Rol con tabla de acceso por módulo",
      "Botón 'Ver permisos' en la página de Usuarios",
      "Eliminado el panel colapsable en favor de la página dedicada",
    ],
  },
  {
    version: "3.32.1",
    date: "2026-03-11",
    type: "patch",
    title: "Mejora de visibilidad de permisos por rol",
    description: "Se reemplazó el tooltip invisible por un popover funcional y se agregó una matriz colapsable de permisos por rol en la página de usuarios.",
    changes: [
      "RolePermissionsTooltip ahora usa Popover en lugar de Tooltip para compatibilidad con Select",
      "Nueva matriz visual de permisos (roles vs módulos) con indicadores de acceso completo, solo lectura y sin acceso",
      "Panel colapsable integrado en la página de Gestión de Usuarios",
    ],
  },
  {
    version: "3.32.0",
    date: "2026-03-11",
    type: "minor",
    title: "Robustecimiento del módulo de Gestión de Usuarios",
    description: "Mejoras significativas en la administración de usuarios: búsqueda, filtrado, estado activo/inactivo, reseteo de contraseña y descripción de permisos por rol.",
    changes: [
      "Columna de email visible en la tabla de usuarios",
      "Barra de búsqueda por nombre o email",
      "Filtro por rol con dropdown",
      "Activar/desactivar usuarios sin eliminarlos (ban/unban)",
      "Botón para resetear contraseña y generar credenciales temporales",
      "Confirmación al cambiar rol con resumen de permisos",
      "Tooltip de permisos por rol (acceso completo vs solo lectura)",
      "Badge 'Tú' junto al usuario actual",
      "Paginación en la tabla de usuarios",
      "Nuevas Edge Functions: reset-user-password, toggle-user-status",
      "Campos email e is_active en tabla profiles con sincronización automática",
    ],
  },
  {
    version: "3.31.0",
    date: "2026-03-11",
    type: "minor",
    title: "Nuevo rol: Ventas",
    description: "Se agregó el rol 'Ventas' orientado al equipo comercial con acceso completo a CRM, clientes y cotizaciones, y lectura en flota, reservas y reportes.",
    changes: [
      "Nuevo valor 'ventas' en el enum de roles",
      "Políticas RLS: acceso completo a clientes, prospectos y cotizaciones",
      "Políticas RLS: lectura en equipos, reservas, actividad, auditoría y documentos",
      "Sidebar y rutas actualizadas con permisos para el rol ventas",
      "Color del rol: teal-600",
    ],
  },
  {
    version: "3.30.2",
    date: "2026-03-11",
    type: "patch",
    title: "Eliminar facturas",
    description: "Se agregó la funcionalidad de eliminar facturas desde el detalle, disponible para los roles Admin y Administrativo.",
    changes: [
      "Opción de eliminar en el menú de acciones del detalle de factura",
      "Confirmación con diálogo antes de eliminar",
      "Restringido a roles admin y administrativo",
    ],
  },
  {
    version: "3.30.1",
    date: "2026-03-11",
    type: "patch",
    title: "Eliminar entregas y recolecciones",
    description: "Se agregó la funcionalidad de eliminar registros de entregas y recolecciones, disponible para los roles Admin y Administrativo.",
    changes: [
      "Botón de eliminar entrega en tabla y vista móvil",
      "Confirmación con diálogo antes de eliminar",
      "Restringido a roles admin y administrativo",
    ],
  },
  {
    version: "3.30.0",
    date: "2026-03-11",
    type: "minor",
    title: "Cotización de renta por modelo de equipo",
    description: "Las cotizaciones de renta ahora se crean seleccionando modelos de equipo con cantidad y tarifas, en lugar de montacargas específicos. Al convertir a reserva, se asignan los equipos físicos disponibles.",
    changes: [
      "Nuevo componente RentalLineItems para cotizaciones de renta por modelo",
      "Tarifas por defecto (diaria, semanal, mensual) en modelos de equipo",
      "Diálogo de asignación de equipos al convertir cotización a reserva",
      "Función generateLineItemsFromModel en invoiceUtils",
      "Compatibilidad con cotizaciones existentes (flujo legacy)",
      "Formulario de modelos de equipo actualizado con campos de tarifas",
    ],
  },
  {
    version: "3.29.2",
    date: "2026-03-11",
    type: "patch",
    title: "Editar cotizaciones enviadas",
    description: "El botón Editar ahora permanece visible cuando una cotización está en estado 'enviada', permitiendo modificarla después de enviarla.",
    changes: [
      "Botón Editar visible en cotizaciones con status draft y sent",
      "Botón Marcar Enviada solo visible en status draft",
    ],
  },
  {
    version: "3.29.1",
    date: "2026-03-11",
    type: "patch",
    title: "Administrativo puede eliminar cotizaciones",
    description: "El rol Administrativo ahora puede eliminar cotizaciones desde la vista de detalle, además de crearlas y editarlas.",
    changes: [
      "Botón de eliminar cotización visible para rol Administrativo",
    ],
  },
  {
    version: "3.29.0",
    date: "2026-03-10",
    type: "minor",
    title: "Descuento por línea en cotizaciones",
    description: "Cada línea de una cotización (renta o venta) ahora puede tener un descuento en porcentaje (%) o monto fijo ($). Se refleja en formulario, vista de detalle, resumen de costos y PDF.",
    changes: [
      "Nuevo campo de descuento por línea con selector de tipo (% o $)",
      "Soporte en cotizaciones de renta y venta",
      "Columna 'Dto.' condicional en tabla de detalle y PDF Premium",
      "Resumen de costos muestra indicador de descuento aplicado",
      "Persistencia automática en JSONB sin migración de base de datos",
    ],
  },
  {
    version: "3.28.0",
    date: "2026-03-10",
    type: "minor",
    title: "Reasignar cliente al convertir cotización genérica",
    description: "Al convertir una cotización de 'Público en General' a reserva, se muestra un diálogo para seleccionar el cliente final antes de proceder.",
    changes: [
      "Diálogo intermedio de reasignación de cliente al detectar 'Público en General'",
      "Actualización automática de la cotización con el cliente seleccionado",
      "Filtrado del cliente genérico en el selector",
    ],
  },
  {
    version: "3.27.0",
    date: "2026-03-10",
    type: "minor",
    title: "Eliminar clientes",
    description: "Los administradores ahora pueden eliminar clientes desde la página de detalle, con validación de dependencias y confirmación.",
    changes: [
      "Botón 'Eliminar' en detalle de cliente (solo admin)",
      "Validación: no se permite eliminar si tiene reservas o facturas",
      "Diálogo de confirmación con AlertDialog",
    ],
  },
  {
    version: "3.26.1",
    date: "2026-03-10",
    type: "patch",
    title: "Eliminar campo Dirección de Facturación",
    description: "Se removió el campo 'Dirección de Facturación' del formulario de cliente. El C.P. Fiscal cubre la parte fiscal del CFDI y el campo 'Dirección' queda como dirección general/de entrega.",
    changes: [
      "Eliminado campo 'Dirección de Facturación' del formulario de cliente",
      "Simplificada la sección de direcciones en el diálogo de cliente",
    ],
  },
  {
    version: "3.26.0",
    date: "2026-03-10",
    type: "minor",
    title: "Importar cliente desde CSF del SAT",
    description: "Al agregar un cliente, ahora se puede subir un PDF de Constancia de Situación Fiscal (CSF) para extraer automáticamente los datos fiscales mediante IA.",
    changes: [
      "Nueva pestaña 'Importar desde CSF' en el diálogo de agregar cliente",
      "Extracción automática de RFC, razón social, C.P. fiscal, dirección y régimen fiscal",
      "Soporte drag-and-drop para subir el PDF",
      "Nueva función backend parse-csf con Lovable AI",
    ],
  },
  {
    version: "3.25.0",
    date: "2026-03-10",
    type: "minor",
    title: "Editar cliente desde página de detalle",
    description: "Se agregó un botón 'Editar' en la página de detalle de cliente que abre un formulario pre-llenado para modificar la información.",
    changes: [
      "Botón 'Editar' con icono en el header de detalle de cliente",
      "Formulario de edición reutilizable extraído como componente compartido (CustomerFormDialog)",
    ],
  },
  {
    version: "3.24.3",
    date: "2026-03-10",
    type: "patch",
    title: "Modelo seleccionado se mantiene al editar equipo",
    description: "Se corrigió un problema donde el dropdown de modelo aparecía vacío al editar un montacargas existente.",
    changes: [
      "Se agregó key al Select de modelo para forzar re-montaje cuando cambia el fabricante",
    ],
  },
  {
    version: "3.24.2",
    date: "2026-03-10",
    type: "patch",
    title: "Selector de cotizaciones muestra todas las opciones",
    description: "El selector de cotización vinculada en el diálogo de prospecto ahora muestra todas las cotizaciones, priorizando las que coinciden con el nombre de empresa.",
    changes: [
      "Se reemplazó el filtro excluyente por un ordenamiento por relevancia",
    ],
  },
  {
    version: "3.24.1",
    date: "2026-03-10",
    type: "patch",
    title: "Columnas Kanban más angostas en CRM",
    description: "Se redujo el ancho de las columnas del pipeline Kanban de 288px a 256px para mejor aprovechamiento del espacio.",
    changes: [
      "Columnas Kanban reducidas de w-72 a w-64",
    ],
  },
  {
    version: "3.24.0",
    date: "2026-03-10",
    type: "minor",
    title: "Persistencia de filtros en todas las páginas de listado",
    description: "Los filtros de búsqueda y estado ahora se sincronizan con la URL en todas las páginas de listado, preservándose al navegar y regresar.",
    changes: [
      "Hook useListFilters migrado de useState a useSearchParams para persistencia automática",
      "Páginas beneficiadas: Facturas, Cotizaciones, Reservas, Contratos, Mantenimiento, Daños y Clientes",
      "Al regresar con la flecha atrás, todos los filtros se restauran automáticamente",
    ],
  },
  {
    version: "3.23.7",
    date: "2026-03-10",
    type: "patch",
    title: "Flecha atrás preserva filtros de búsqueda",
    description: "El botón de retroceso en páginas de detalle ahora usa el historial del navegador para conservar los filtros activos al regresar.",
    changes: [
      "DetailPageHeader usa navigate(-1) en lugar de ruta fija para preservar query params",
      "Fallback a ruta fija (backTo) cuando no hay historial previo",
    ],
  },
  {
    version: "3.23.6",
    date: "2026-03-10",
    type: "patch",
    title: "Persistencia de filtros en Inventario de Flota",
    description: "Los filtros de búsqueda y estado se conservan en la URL al navegar a un detalle y volver con el botón atrás.",
    changes: [
      "Filtros de búsqueda y estado sincronizados con query params de la URL",
      "Al volver con el botón atrás, los filtros se restauran automáticamente",
    ],
  },
  {
    version: "3.23.5",
    date: "2026-03-09",
    type: "patch",
    title: "Reorden del Estado de Resultados",
    description: "Se reordenó el Estado de Resultados para mostrar Total de Egresos antes de Depreciación, ya que esta no es una salida de efectivo.",
    changes: [
      "Total Egresos ahora excluye depreciación de equipos",
      "Depreciación se muestra como deducción separada antes de Utilidad Neta",
      "Aplicado en vista mensual y comparativa YoY",
    ],
  },
  {
    version: "3.23.4",
    date: "2026-03-09",
    type: "patch",
    title: "Simplificación de tabla de flota",
    description: "Se eliminaron las columnas Fabricante, Capacidad y Altura de la tabla de inventario de flota para simplificar la vista.",
    changes: [
      "Eliminada columna Fabricante",
      "Eliminada columna Capacidad",
      "Eliminada columna Altura",
      "Actualizado export CSV y vista móvil",
    ],
  },
  {
    version: "3.23.3",
    date: "2026-03-09",
    type: "patch",
    title: "Columna No. de Serie en inventario de flota",
    description: "Se agregó la columna 'No. de Serie' a la tabla de inventario de flota, visible en desktop, móvil, búsqueda y exportación CSV.",
    changes: [
      "Nueva columna sorteable 'No. de Serie' entre Fabricante y Capacidad",
      "Búsqueda incluye número de serie",
      "Exportación CSV incluye número de serie",
      "Tarjetas móviles muestran S/N cuando existe",
    ],
  },
  {
    version: "3.23.2",
    date: "2026-03-09",
    type: "patch",
    title: "Fix precarga de fabricante y modelo al editar montacargas",
    description: "Corregido bug donde los campos Fabricante y Modelo aparecían vacíos al editar un montacargas existente.",
    changes: [
      "Sincronizado el llenado del formulario con la carga de modelos de equipo",
      "Agregado fallback para mostrar valores guardados aunque no estén en el catálogo",
    ],
  },
  {
    version: "3.23.1",
    date: "2026-03-09",
    type: "patch",
    title: "Eliminar diálogo de factura post-devolución",
    description: "Se removió el diálogo automático que preguntaba si generar factura al completar una inspección de devolución.",
    changes: [
      "Eliminado el diálogo PostInspectionInvoiceDialog del flujo de devoluciones",
      "El flujo ahora es: completar devolución → toast de éxito → cerrar",
    ],
  },
  {
    version: "3.23.0",
    date: "2026-03-09",
    type: "minor",
    title: "Módulo de Proveedores",
    description: "Nuevo módulo completo de Proveedores integrado al ERP, con vinculación a gastos operativos y registros de mantenimiento.",
    changes: [
      "Tabla de proveedores con RLS, auditoría y actividad",
      "Página de listado con búsqueda, ordenamiento, paginación y exportación CSV",
      "Página de detalle con datos de contacto, fiscales, gastos y mantenimiento vinculados",
      "Selector de proveedor en formularios de gastos operativos y mantenimiento",
      "Columna supplier_id en operating_expenses y maintenance_logs",
      "Navegación en sidebar bajo Administración",
    ],
  },
  {
    version: "3.22.2",
    date: "2026-03-09",
    type: "patch",
    title: "Corrección de rango de fechas en Estado de Resultados",
    description: "Se corrigió un bug donde el mes seleccionado en 'Hasta' no se incluía completamente debido a interpretación UTC de fechas.",
    changes: [
      "Construcción de fechas con parámetros locales en lugar de cadenas ISO para evitar desfase por zona horaria",
    ],
  },
  {
    version: "3.22.1",
    date: "2026-03-09",
    type: "patch",
    title: "Selector de rango por mes en Estado de Resultados",
    description: "El selector de fechas del Estado de Resultados ahora permite elegir meses completos en lugar de días individuales, alineándose con la naturaleza mensual de los estados financieros.",
    changes: [
      "Reemplazo de selector de rango por día con dos selectores de mes (Desde / Hasta)",
      "Opciones dinámicas de los últimos 24 meses en español",
      "Cálculo automático del primer y último día del mes seleccionado",
    ],
  },
  {
    version: "3.22.0",
    date: "2026-03-09",
    type: "minor",
    title: "Módulo independiente de Estado de Resultados",
    description: "El Estado de Resultados ahora tiene su propia entrada en el sidebar para acceso directo, manteniendo también su disponibilidad dentro del módulo de Reportes.",
    changes: [
      "Nueva página standalone de Estado de Resultados con selector de fechas propio",
      "Entrada dedicada en sidebar bajo sección Administración",
      "Acceso restringido a roles admin, administrativo y auditor",
      "Se mantiene disponible también dentro del módulo de Reportes",
    ],
  },
  {
    version: "3.21.0",
    date: "2026-03-09",
    type: "minor",
    title: "Depreciación de equipos rentados en Estado de Resultados",
    description: "El Estado de Resultados ahora calcula automáticamente la depreciación mensual (costo de adquisición / 36 meses) únicamente para montacargas que tuvieron rentas activas en cada mes.",
    changes: [
      "Nueva fila 'Depreciación (Equipos Rentados)' en el Estado de Resultados",
      "Cálculo automático de depreciación línea recta a 36 meses solo para equipos con rentas activas",
      "Ajuste de Utilidad Neta: ahora resta depreciación de equipos rentados",
      "Incluido en tabla estándar, comparativo YoY, gráficas, exportación CSV y PDF",
      "Montacargas sin costo de adquisición se omiten del cálculo",
    ],
  },
  {
    version: "3.20.0",
    date: "2026-03-09",
    type: "minor",
    title: "Refactorización de código y consolidación de patrones",
    description: "Mejora significativa de la arquitectura del código: consolidación del hook useListPage en todas las páginas de lista, estandarización de manejo de errores con sonner, y nuevo hook useDialogState para gestión de diálogos.",
    changes: [
      "Nuevo hook useDialogState para gestión unificada de estados de diálogos con formularios",
      "Migración de 6 páginas de lista a usar useListPage: BookingsPage, ContractsPage, QuotesPage, InvoicesPage, CustomersPage, Fleet",
      "Eliminación de imports redundantes de useSort, usePagination, useIsMobile en páginas migradas",
      "Estandarización de error handling: useBookings, useInvoices, useForklifts, useQuotes ahora usan sonner directamente",
      "Eliminación de dynamic imports de toast en favor de imports estáticos de sonner",
      "Reducción de ~20-30 líneas de boilerplate por página",
    ],
  },
  {
    version: "3.19.10",
    date: "2026-03-08",
    type: "patch",
    title: "Remover botón de nueva reserva en calendario",
    description: "Se eliminó el botón de 'Nueva Reserva' en la página de calendario para centrar la vista exclusivamente en la disponibilidad.",
    changes: [
      "Se quitó la propiedad action del PageHeader en CalendarPage.tsx",
    ],
  },
  {
    version: "3.19.9",
    date: "2026-03-08",
    type: "patch",
    title: "Enlace directo a reservas desde mensaje de devoluciones",
    description: "El mensaje informativo en el formulario de devolución ahora incluye un enlace directo a la página de reservas para facilitar el ajuste de fechas.",
    changes: [
      "Enlace clickeable 'edita la reserva' que abre la página de reservas en nueva pestaña",
    ],
  },
  {
    version: "3.19.8",
    date: "2026-03-08",
    type: "patch",
    title: "Filtrar solo reservas terminadas en devoluciones",
    description: "El formulario de nueva devolución ahora solo muestra reservas cuyo periodo de renta ya finalizó, con mensaje informativo para el usuario.",
    changes: [
      "Filtro de activeBookings validando que end_date <= hoy",
      "Mensaje informativo debajo del selector de reserva",
    ],
  },
  {
    version: "3.19.7",
    date: "2026-03-08",
    type: "patch",
    title: "Campo de fecha en formulario de Nueva Devolución",
    description: "Se agregó un selector de fecha al formulario de nueva inspección de devolución para poder registrar inspecciones con fecha diferente a la actual.",
    changes: [
      "Nuevo campo DatePickerField en el diálogo de Nueva Devolución",
      "Parámetro p_inspected_at agregado a la función complete_return_inspection",
      "Valor predeterminado: fecha actual",
    ],
  },
  {
    version: "3.19.6",
    date: "2026-03-08",
    type: "patch",
    title: "Filtro de fecha en Inspección de Devolución",
    description: "Se agregó un selector de fecha para filtrar inspecciones por día en la tabla de devoluciones.",
    changes: [
      "Nuevo filtro DatePickerField en la página de Devoluciones",
      "Filtrado client-side por fecha de inspección",
      "Botón para limpiar el filtro",
    ],
  },
  {
    version: "3.19.5",
    date: "2026-03-08",
    type: "patch",
    title: "Diferenciar colores de Confirmado y Completado",
    description: "Se asignó un color gris-azul oscuro al estado 'Completado' para distinguirlo del verde de 'Confirmado'.",
    changes: [
      "Nuevo token --status-completed (gris-azul oscuro)",
      "StatusBadge usa bg-status-completed para el estado completado",
      "Confirmado mantiene verde, Completado ahora es gris-azul",
    ],
  },
  {
    version: "3.19.4",
    date: "2026-03-08",
    type: "patch",
    title: "Mejora de diseño en PDF de facturas",
    description: "Se aplicaron las mismas mejoras de jerarquía visual (etiquetas bold/normal) a la tarjeta de Detalles del PDF de facturas.",
    changes: [
      "Etiquetas 'Emitida' y 'Vence' en negrita con valores en texto normal",
      "Consistencia visual con el PDF de cotizaciones",
    ],
  },
  {
    version: "3.19.3",
    date: "2026-03-08",
    type: "patch",
    title: "Mejora en sección de Periodo del PDF de cotización",
    description: "Se mejoró la presentación del periodo de renta en la tarjeta de Detalles del PDF, separando fechas de inicio y fin con etiquetas claras.",
    changes: [
      "Reemplazado carácter Unicode → por etiquetas 'Inicio' y 'Fin' separadas",
      "Agregado formato bold/normal para mejor jerarquía visual",
      "Cambiado 'Vigencia' por 'Vigencia hasta' para mayor claridad",
    ],
  },
  {
    version: "3.19.2",
    date: "2026-03-08",
    type: "patch",
    title: "Corrección de PDF de cotización y datos fiscales del cliente",
    description: "Se corrigieron solapamientos de texto en el encabezado del PDF, se ajustó el logo y se agregó RFC y C.P. del cliente en la tarjeta de información.",
    changes: [
      "Reducido tamaño de fuente del título y nombre de empresa para evitar solapamiento",
      "Ajustada posición del logo en el encabezado",
      "Limitado ancho del nombre de empresa con maxWidth",
      "Agregado RFC y C.P. del cliente en la tarjeta de Cliente del PDF",
      "Aumentada altura de tarjeta de cliente para acomodar datos fiscales",
    ],
  },
  {
    version: "3.19.1",
    date: "2026-03-08",
    type: "patch",
    title: "Hover estandarizado en tablas clickeables",
    description: "Se unificó el efecto hover en todas las tablas con filas clickeables (Clientes, Flota) para usar el mismo estilo que Contratos, Cotizaciones, Facturas y Auditoría.",
    changes: [
      "Agregado borde izquierdo al hover en filas de Clientes",
      "Cambiado color de hover en Flota de accent a muted para consistencia",
    ],
  },
  {
    version: "3.19.0",
    date: "2026-03-08",
    type: "minor",
    title: "RFC y C.P. en tarjeta de cliente (cotización)",
    description: "Se muestran el RFC y código postal del cliente en la tarjeta de Cliente del detalle de cotización.",
    changes: [
      "Agregado RFC y C.P. en la tarjeta de cliente del detalle de cotización",
    ],
  },
  {
    version: "3.18.9",
    date: "2026-03-08",
    type: "patch",
    title: "Eliminar botones redundantes en tabla de clientes",
    description: "Se eliminaron los botones Ver/Editar de la tabla de clientes ya que la fila completa es clickeable.",
    changes: [
      "Eliminada columna de acciones redundante en tabla de clientes",
    ],
  },
  {
    version: "3.18.8",
    date: "2026-03-08",
    type: "patch",
    title: "Filas de clientes clickeables",
    description: "Al hacer clic en cualquier parte de la fila de un cliente se navega a su detalle.",
    changes: [
      "Filas de la tabla de clientes ahora son clickeables para abrir el detalle",
      "Botones de acción mantienen su comportamiento independiente",
    ],
  },
  {
    version: "3.18.6",
    date: "2026-03-08",
    type: "patch",
    title: "Diseño premium PDF en facturas",
    description: "Aplicado el diseño gráfico profesional a las facturas PDF: barra accent navy, tarjetas de receptor y detalles, badge de estado, tabla premium, totales destacados y pie de página corporativo.",
    changes: [
      "Facturas con la misma estructura visual que las cotizaciones",
      "Tarjeta de receptor con RFC y régimen fiscal",
      "Badge de estado (Pagada/Pendiente/Cancelada) con color semafórico",
      "Badge verde 'Timbrado SAT' cuando tiene CFDI",
      "Información de forma y método de pago integrada",
      "QR placeholder y leyenda CFDI estilizados",
    ],
  },
  {
    version: "3.18.5",
    date: "2026-03-08",
    type: "patch",
    title: "Rediseño profesional del PDF de cotizaciones",
    description: "Las cotizaciones ahora se generan con un diseño premium: barra de acento navy, tarjetas de información, tabla con header navy y filas alternadas, total destacado, términos y condiciones automáticos, y pie de página corporativo.",
    changes: [
      "Barra superior navy con línea dorada como acento de marca",
      "Encabezado con logo, datos de empresa y número de cotización destacado",
      "Tarjetas de info lado a lado para cliente y detalles del periodo",
      "Tabla de conceptos con header navy/texto blanco y filas alternadas",
      "Total en caja navy con tipografía dorada",
      "Sección de términos y condiciones automática",
      "Pie de página con datos de la empresa",
    ],
  },
  {
    version: "3.18.4",
    date: "2026-03-08",
    type: "minor",
    title: "Conversión de prospecto a cliente",
    description: "Los prospectos en etapa 'Cerrado Ganado' pueden convertirse en clientes registrados con un clic. Los datos se pre-llenan automáticamente.",
    changes: [
      "Botón 'Convertir a Cliente' en prospectos cerrados ganados",
      "Pre-llenado automático de nombre, contacto, email y teléfono",
      "Vinculación automática del prospecto con el cliente creado",
      "Badge 'Cliente creado' con enlace directo al detalle del cliente",
    ],
  },
  {
    version: "3.18.3",
    date: "2026-03-08",
    type: "patch",
    title: "Vinculación de prospectos con cotizaciones",
    description: "Los prospectos CRM ahora pueden vincularse a cotizaciones existentes. Al mover a 'Cotización Enviada', el valor del trato es obligatorio y se auto-llena al seleccionar una cotización.",
    changes: [
      "Nuevo selector de cotización en el formulario de prospecto",
      "Valor del trato obligatorio (> $0) desde etapa Cotización Enviada en adelante",
      "Auto-llenado del valor al vincular cotización",
      "Badge clicable con número de cotización en las tarjetas del Kanban",
      "Navegación directa al detalle de la cotización desde el pipeline",
    ],
  },
  {
    version: "3.18.2",
    date: "2026-03-08",
    type: "patch",
    title: "Diálogo de validación al mover prospectos",
    description: "Al arrastrar un prospecto a otra etapa del pipeline, se abre automáticamente el formulario de edición para validar o actualizar campos como el valor del trato.",
    changes: [
      "Diálogo de edición se abre al cambiar etapa por drag-and-drop",
      "Indicador visual de etapa origen → destino en el diálogo",
      "Cancelar el diálogo deja el prospecto en su etapa original",
      "Reordenar dentro de la misma columna no abre diálogo",
    ],
  },
  {
    version: "3.18.1",
    date: "2026-03-08",
    type: "patch",
    title: "Reorganización del Sidebar",
    description: "Reestructuración de la navegación lateral en 5 grupos lógicos siguiendo el flujo del negocio.",
    changes: [
      "Nuevo grupo 'Comercial': CRM, Clientes, Cotizaciones, Reservas",
      "Grupo 'Operaciones' enfocado: Contratos, Entregas, Devoluciones, Facturas",
      "Refacciones absorbido en 'Flota y Mantenimiento'",
      "Administración reordenada: Gastos y Reportes priorizados",
    ],
  },
  {
    version: "3.18.0",
    date: "2026-03-08",
    type: "minor",
    title: "Pipeline de Ventas CRM",
    description: "Nuevo tablero Kanban drag-and-drop para rastrear prospectos de venta a través de 6 etapas.",
    changes: [
      "Nueva página Pipeline CRM con tablero tipo Trello",
      "6 etapas: Nuevo Prospecto, Contactado, Cotización Enviada, Negociación, Cerrado Ganado, Cerrado Perdido",
      "Drag & drop entre columnas para mover prospectos",
      "Tarjetas con empresa, contacto y valor del trato en MXN",
      "Diálogo para crear, editar y eliminar prospectos",
      "Totales por columna visibles en el encabezado",
    ],
  },
  {
    version: "3.17.11",
    date: "2026-03-08",
    type: "patch",
    title: "Alerta de Póliza Faltante al Crear Reserva",
    description: "Al crear una reserva, si el montacargas no tiene póliza de mantenimiento activa, se ofrece crearla inmediatamente.",
    changes: [
      "Nuevo diálogo PostBookingPolicyDialog para crear póliza post-reserva",
      "Detección automática de póliza faltante al confirmar reserva",
      "Flujo encadenado: Entrega → Póliza → Calendario",
    ],
  },
  {
    version: "3.17.10",
    date: "2026-03-08",
    type: "minor",
    title: "Mantenimiento Recurrente con Póliza de Proveedor Externo",
    description: "Genera automáticamente registros de mantenimiento mensual para cada montacargas rentado con póliza activa de proveedor externo.",
    changes: [
      "Nueva tabla 'maintenance_policies' para configurar pólizas por montacargas",
      "Pestaña 'Pólizas de Mantenimiento' en Configuración de Operaciones con CRUD completo",
      "Edge Function 'generate-recurring-maintenance' ejecutable por cron o manualmente",
      "Botón 'Generar Recurrente' en página de Mantenimiento (admin/administrativo)",
      "'Póliza de Mantenimiento' agregado como tipo de servicio",
      "Control de duplicados con campo last_generated_month",
    ],
  },
  {
    version: "3.17.9",
    date: "2026-03-08",
    type: "minor",
    title: "Integración Inventario ↔ Mantenimiento",
    description: "Los mecánicos pueden agregar refacciones usadas directamente desde el tablero Kanban. El sistema descuenta stock automáticamente y actualiza el costo del mantenimiento.",
    changes: [
      "Sección 'Refacciones Utilizadas' en el detalle de cada tarea de mantenimiento",
      "Combobox buscable por nombre o SKU con alerta de stock bajo",
      "Al agregar refacción: inserta en maintenance_parts, descuenta stock vía trigger, suma costo al log",
      "Sheet lateral al hacer clic en tarjeta del Kanban con info completa y gestión de refacciones",
      "Costo total del mantenimiento se actualiza en tiempo real",
    ],
  },
  {
    version: "3.17.8",
    date: "2026-03-08",
    type: "minor",
    title: "Página de Control de Refacciones",
    description: "Nueva página de inventario de refacciones con tabla, búsqueda, filtro por categoría, alertas de stock bajo y formulario de alta/edición.",
    changes: [
      "Página InventoryPage con tabla de refacciones y acciones CRUD",
      "Badge destructive 'Reabastecer' cuando stock ≤ mínimo",
      "Formulario con validación Zod en español mexicano",
      "Sección 'Inventario' en sidebar con icono Package",
      "Schema partFormSchema centralizado en formSchemas.ts",
    ],
  },
  {
    version: "3.17.7",
    date: "2026-03-08",
    type: "minor",
    title: "Módulo de Control de Refacciones — Infraestructura",
    description: "Nuevas tablas parts_inventory y maintenance_parts con RLS, trigger de descuento automático de stock y hooks React Query para CRUD completo.",
    changes: [
      "Tabla parts_inventory con categorías, stock mínimo y costo unitario",
      "Tabla maintenance_parts como junction con maintenance_logs",
      "Trigger handle_part_usage para decrementar stock automáticamente",
      "RLS: lectura para staff, escritura para admin/administrativo/mechanic",
      "Hook usePartsInventory con CRUD completo y useMaintenanceParts",
    ],
  },
  {
    version: "3.17.6",
    date: "2026-03-07",
    type: "minor",
    title: "Alerta de Rentas Vencidas en el Panel",
    description: "Nueva alerta en el dashboard que muestra reservas confirmadas cuya fecha de fin ya pasó y no se ha registrado devolución, con acceso directo al módulo de devoluciones.",
    changes: [
      "Nueva sección 'Rentas Vencidas' en AlertsRow del dashboard",
      "Función get_dashboard_stats actualizada con campo overdue_bookings",
      "Muestra nombre del equipo, cliente y días de retraso",
      "Botón de acción navega a /returns con booking_id pre-seleccionado",
    ],
  },
  {
    version: "3.17.5",
    date: "2026-03-07",
    type: "patch",
    title: "Eliminar carta de Reservas del Calendario",
    description: "Se eliminó la carta duplicada de reservas del módulo de calendario ya que esta información está disponible en el módulo dedicado de reservas.",
    changes: [
      "Eliminada carta de 'Reservas' con filtros de estado del CalendarPage",
      "Limpieza de imports y estado no utilizados",
    ],
  },
  {
    version: "3.17.4",
    date: "2026-03-07",
    type: "patch",
    title: "Devolución anticipada abre formulario completo de devoluciones",
    description: "El botón 'Devolución Anticipada' en reservas ahora navega al módulo de devoluciones con la reserva pre-seleccionada, usando el mismo flujo de inspección completo.",
    changes: [
      "Botón 'Devolución Anticipada' navega a /returns con booking_id",
      "ReturnInspectionPage auto-abre dialog y pre-selecciona reserva desde query param",
      "Eliminado dialog inline de devolución anticipada en BookingActions",
    ],
  },
  {
    version: "3.17.3",
    date: "2026-03-07",
    type: "patch",
    title: "Fix paréntesis vacíos en contacto de reserva",
    description: "Corregido renderizado de '()' cuando el contacto del cliente está vacío en la tarjeta de reservas del calendario.",
    changes: [
      "Renderizado condicional del contacto del cliente en CalendarPage",
    ],
  },
  {
    version: "3.17.2",
    date: "2026-03-07",
    type: "patch",
    title: "UI mejorada de Gastos Operativos",
    description: "Tarjeta de total, barra de búsqueda, badges de categoría y empty state mejorado en la página de gastos.",
    changes: [
      "Tarjeta resumen 'Total de Gastos' con formatCurrency",
      "SearchBar para filtrar por descripción",
      "Badge con variante secondary para costo_venta y outline para el resto",
      "EmptyRow en lugar de EmptyState para tabla vacía con headers visibles",
    ],
  },
  {
    version: "3.17.1",
    date: "2026-03-07",
    type: "patch",
    title: "Formulario de Registro de Gastos con Validación",
    description: "Nuevo diálogo ExpenseFormDialog con react-hook-form + zod para registrar gastos con validación inline en español.",
    changes: [
      "Componente ExpenseFormDialog con validación zod y mensajes en español mexicano",
      "Schema expenseFormSchema centralizado en formSchemas.ts",
      "Errores inline bajo cada campo en lugar de toasts genéricos",
      "Categoría 'Costo de Venta (Directo)' explícita en el selector",
    ],
  },
  {
    version: "3.17.0",
    date: "2026-03-07",
    type: "minor",
    title: "Mejoras al Estado de Resultados",
    description: "Comparativo año vs año, gráfica de utilidad neta, margen bruto y exportación a PDF en el reporte de Estado de Resultados.",
    changes: [
      "Modo 'Comparativo' año vs año con variación absoluta y porcentual",
      "Gráfica de área de Utilidad Neta mensual con línea de referencia en cero",
      "Fila de Margen Bruto (%) después de Utilidad Bruta",
      "Botón de exportar a PDF con encabezado de empresa y formato contable",
    ],
  },
  {
    version: "3.16.2",
    date: "2026-03-07",
    type: "patch",
    title: "Filtro por año en Estado de Resultados",
    description: "Selector de año en el reporte de Estado de Resultados para separar datos por período anual.",
    changes: [
      "Selector de año (Todos / 2025 / 2026 / etc.) en el encabezado del reporte",
      "KPIs, gráfica, tabla y CSV se filtran según el año seleccionado",
      "Años disponibles se detectan dinámicamente de los datos",
    ],
  },
  {
    version: "3.16.1",
    date: "2026-03-07",
    type: "patch",
    title: "Mejora y estandarización de tablas",
    description: "Tablas mejoradas con filas zebra, encabezados sticky, bordes definidos y densidad compacta en toda la app.",
    changes: [
      "Filas zebra con fondo alternado para mejor legibilidad",
      "Encabezados sticky que permanecen fijos al hacer scroll",
      "Bordes y separadores mejorados con fondo en header",
      "Densidad compacta: padding reducido para mostrar más datos",
      "Encabezados en mayúsculas con tracking amplio para jerarquía visual",
    ],
  },
  {
    version: "3.16.0",
    date: "2026-03-07",
    type: "minor",
    title: "Costo de Venta de Montacargas",
    description: "Campo de costo de adquisición en montacargas y generación automática de gasto operativo al vender un equipo.",
    changes: [
      "Nuevo campo 'Costo de Adquisición' en formulario y detalle de montacargas",
      "Nueva categoría de gasto 'Costo de Venta' en gastos operativos",
      "Al cambiar status a 'Vendido', se genera automáticamente un gasto con el costo de adquisición",
      "Estado de Resultados incluye '(-) Costo de Venta' como costo directo antes de Utilidad Bruta",
    ],
  },
  {
    version: "3.15.2",
    date: "2026-03-07",
    type: "patch",
    title: "Estado de Resultados en formato vertical",
    description: "Tabla del Estado de Resultados transpuesta al formato contable tradicional: conceptos como filas y meses como columnas.",
    changes: [
      "Tabla transpuesta: conceptos financieros de arriba a abajo, meses de izquierda a derecha",
      "Filas de subtotal (Utilidad Bruta, Utilidad Neta) con estilo diferenciado",
      "Costos con prefijo (-) y color rojo para fácil identificación",
      "Columna sticky de conceptos para scroll horizontal",
    ],
  },
  {
    version: "3.15.1",
    date: "2026-03-07",
    type: "patch",
    title: "Estado de Resultados mejorado",
    description: "Reporte de Estado de Resultados con KPIs, gráfica de barras apiladas por categoría de gasto, utilidad bruta y total de egresos.",
    changes: [
      "4 tarjetas KPI: Ingresos, Total Egresos, Utilidad Neta, Margen Neto con colores condicionales",
      "Gráfica de barras apiladas desglosando costos por categoría (mantenimiento, daños, renta, nómina, etc.)",
      "Columna de Utilidad Bruta separando costos directos de gastos operativos",
      "Columna de Total Egresos explícita",
      "Todas las categorías de gastos siempre visibles para consistencia",
    ],
  },
  {
    version: "3.15.0",
    date: "2026-03-07",
    type: "minor",
    title: "Gastos Recurrentes",
    description: "Permite marcar gastos operativos como recurrentes mensuales y generarlos automáticamente con un solo clic.",
    changes: [
      "Switch 'Gasto recurrente mensual' en el formulario de crear/editar gastos",
      "Badge visual 'Mensual' en la tabla para identificar gastos recurrentes",
      "Botón 'Generar Recurrentes' que crea automáticamente los gastos del mes actual evitando duplicados",
      "Nueva columna 'is_recurring' en la base de datos",
    ],
  },
  {
    version: "3.14.1",
    date: "2026-03-07",
    type: "patch",
    title: "Prefijo $ en campo de monto de gastos",
    description: "Se agrega el símbolo de peso mexicano ($) como prefijo visual en el campo de monto del diálogo de gastos operativos.",
    changes: [
      "Prefijo '$' visible en el campo de monto del formulario de gastos",
      "Placeholder actualizado a '0.00' con formato mexicano",
    ],
  },
  {
    version: "3.14.0",
    date: "2026-03-07",
    type: "minor",
    title: "Módulo de Gastos Operativos y Estado de Resultados mejorado",
    description: "Nueva tabla y página CRUD para registrar gastos operativos (renta, nómina, software, depreciación, otros). El Estado de Resultados ahora incluye todas las categorías de gastos para calcular utilidad neta.",
    changes: [
      "Nueva página 'Gastos Operativos' con formulario para registrar, editar y eliminar gastos",
      "Categorías de gasto: Renta, Nómina, Software, Depreciación, Otro",
      "Filtro por categoría en la lista de gastos",
      "Estado de Resultados actualizado: muestra columnas dinámicas por cada categoría de gasto con datos",
      "Cálculo de Utilidad Neta = Ingresos - Mantenimiento - Daños - Gastos Operativos",
      "Entrada en sidebar bajo Administración con acceso para admin, administrativo y auditor",
      "Exportación CSV del Estado de Resultados incluye todas las categorías",
    ],
  },
  {
    version: "3.13.0",
    date: "2026-03-07",
    type: "minor",
    title: "Reporte Estado de Resultados mensual",
    description: "Nuevo reporte financiero que muestra ingresos (sin IVA), costos de mantenimiento, costos de daños, utilidad bruta y margen por mes.",
    changes: [
      "Nuevo reporte 'Estado de Resultados' en la sección de Reportes",
      "Tabla mensual con ingresos, costos de mantenimiento, costos de daños, utilidad bruta y margen %",
      "Gráfica de barras comparando ingresos vs costos por mes",
      "Fila de totales acumulados",
      "Exportación a CSV",
    ],
  },
  {
    version: "3.12.2",
    date: "2026-03-07",
    type: "patch",
    title: "Badge de fotos en tabla de daños",
    description: "Cada fila de daño muestra un contador de fotos para identificar rápidamente cuáles tienen evidencia fotográfica.",
    changes: [
      "Badge con ícono de cámara y conteo de fotos en cada fila de la tabla de daños",
      "Visible tanto en vista de escritorio como en tarjetas móviles",
      "Consulta optimizada que obtiene los conteos en una sola petición",
    ],
  },
  {
    version: "3.12.1",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos integradas en reporte de daño",
    description: "Ahora puedes adjuntar fotos directamente al reportar un daño manual, sin necesidad de crear el registro primero.",
    changes: [
      "Zona de drag-and-drop para fotos dentro del diálogo 'Reportar Daño'",
      "Previews locales antes de subir, con opción de eliminar",
      "Las fotos se suben automáticamente al crear el registro de daño",
    ],
  },
  {
    version: "3.12.0",
    date: "2026-03-07",
    type: "minor",
    title: "Reporte manual de daños",
    description: "Los operadores ahora pueden reportar daños encontrados en almacén sin necesidad de una inspección de devolución.",
    changes: [
      "Nuevo diálogo 'Reportar Daño' en la página de Seguimiento de Daños",
      "Selección de montacargas de todo el inventario, cliente opcional, descripción y costo estimado",
      "Disponible para roles admin, administrativo, despachador y mecánico",
    ],
  },
  {
    version: "3.11.2",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos por registro de daño en seguimiento",
    description: "Cada registro de daño ahora tiene su propia sección expandible de fotos con carga drag-and-drop y galería lightbox.",
    changes: [
      "Filas expandibles en DamageTrackingPage: clic en una fila revela la sección de fotos de ese daño",
      "Soporte completo en móvil con toggle para ver/subir fotos por daño",
      "Cada registro usa su ID como entidad para almacenar fotos independientes",
    ],
  },
  {
    version: "3.11.1",
    date: "2026-03-07",
    type: "patch",
    title: "Fotos en inspección de devolución",
    description: "Se agregó el componente de carga de fotos drag-and-drop al formulario de inspección de devolución.",
    changes: [
      "DragDropImageUploader integrado en el diálogo de nueva inspección de devolución",
      "Permite capturar fotos del estado del equipo durante la inspección desde móvil o escritorio",
    ],
  },
  {
    version: "3.11.0",
    date: "2026-03-07",
    type: "minor",
    title: "Fotos de daño con drag-and-drop y galería lightbox",
    description: "Nuevo sistema de captura de fotos con arrastrar y soltar, cámara móvil y galería de imágenes a pantalla completa con navegación táctil.",
    changes: [
      "Nuevo componente DragDropImageUploader con react-dropzone: drag-and-drop, previsualización y captura de cámara en móvil",
      "Nuevo componente ImageGalleryLightbox con navegación por teclado, swipe táctil, zoom y tira de miniaturas",
      "Sección DamagePhotosSection integrada en ForkliftDetail para ver y subir fotos de daño",
      "Componente reutilizable para cualquier entidad que necesite gestión de fotos",
    ],
  },
  {
    version: "3.10.0",
    date: "2026-03-07",
    type: "minor",
    title: "Tablero Kanban para mantenimiento",
    description: "Vista de tablero drag-and-drop para gestionar el estado de trabajo de los registros de mantenimiento con 4 columnas.",
    changes: [
      "Nueva vista Kanban en la página de mantenimiento con columnas: Pendiente, En Progreso, Esperando Refacciones y Completado",
      "Drag-and-drop entre columnas actualiza el estado de trabajo en la base de datos con actualización optimista",
      "Toggle para alternar entre vista de lista y vista de tablero",
      "Nueva columna work_status en maintenance_logs con valor por defecto 'pending'",
      "Componente MaintenanceKanban reutilizable con @hello-pangea/dnd",
    ],
  },
  {
    version: "3.9.0",
    date: "2026-03-07",
    type: "minor",
    title: "Firma electrónica en entregas y skeleton de carga en listas",
    description: "Nuevo componente de firma digital para completar entregas, y eliminación de layout shift en todas las páginas de lista con skeletons alineados a columnas.",
    changes: [
      "Nuevo componente SignaturePad con canvas táctil, deshacer y limpiar",
      "Diálogo de firma del cliente al marcar una entrega como completada",
      "Opción de omitir firma para completar sin captura",
      "Firma guardada como base64 en columna signature_base64 de deliveries",
      "Skeleton de carga alineado a columnas en BookingsPage (7 cols), Fleet (8 cols), InvoicesPage (7), ContractsPage (7), QuotesPage (7) y CustomersPage (6)",
      "Componente TableSkeleton mejorado con prop columnCount para renderizar tabla con celdas skeleton",
      "ListPageLayout acepta skeletonColumns para eliminar layout shift durante carga",
    ],
  },
  {
    version: "3.8.0",
    date: "2026-03-07",
    type: "minor",
    title: "Empty states, loading states y localización MXN",
    description: "Mejoras de UX en formularios, estados vacíos rediseñados y correcciones de localización en moneda y fechas.",
    changes: [
      "Nuevo componente EmptyState con icono, título, subtítulo y botón de acción",
      "Empty states aplicados automáticamente en Reservas, Flota y Facturas vía ListPageLayout",
      "Spinner de carga y texto 'Guardando…' en botones de envío de Reservas, Facturas y Contratos",
      "ContractForm migrado al componente compartido FormActions",
      "Botón Cancelar deshabilitado durante envío para prevenir navegación accidental",
    ],
  },
  {
    version: "3.7.0",
    date: "2026-03-07",
    type: "minor",
    title: "Localización completa a pesos mexicanos y español",
    description: "Correcciones de formato de moneda y fechas para garantizar consistencia en toda la aplicación.",
    changes: [
      "Meses en español (Ene, Feb…) en reporte de Ingresos vía locale es de date-fns",
      "Contratos PDF usan formatCurrency en lugar de .toFixed(2) para tarifas y depósito",
      "Eliminada función duplicada fmtMXN en pdfHelpers.ts, reemplazada por formatCurrency centralizado",
      "Limpieza de imports no usados en QuotePDFButton e InvoicePDFButton",
      "Spinner de carga con marca 'Cargando LiftGo…' en App.tsx",
    ],
  },
  {
    version: "3.6.2",
    date: "2026-03-05",
    type: "patch",
    title: "Admins pueden editar facturas en cualquier estado",
    description: "Los usuarios con rol admin ahora pueden editar facturas independientemente de su estado (enviada, vencida, pagada, parcial).",
    changes: [
      "Botón 'Editar' visible para admins en todos los estados de factura",
      "Usuarios no-admin mantienen la restricción de solo editar borradores",
    ],
  },
  {
    version: "3.6.1",
    date: "2026-03-04",
    type: "patch",
    title: "Corrección de selector de montacargas",
    description: "El selector de montacargas ahora muestra fabricante y modelo en lugar del ID interno.",
    changes: [
      "Formato cambiado de '{ID} — {modelo}' a '{fabricante} {modelo} — {ID}' en selectores",
      "Corrección aplicada en selector simple y multi-selector de cotizaciones",
    ],
  },
  {
    version: "3.6.0",
    date: "2026-03-04",
    type: "minor",
    title: "Refactorización de código",
    description: "Reorganización y limpieza del código para mejorar mantenibilidad, reducir duplicación y facilitar futuras extensiones.",
    changes: [
      "Helpers PDF reutilizables en pdfHelpers.ts (header, tabla de partidas, totales, notas)",
      "Nuevo hook useListPage que combina useSort + usePagination + useIsMobile",
      "ContractPDFButton dividido en 3 archivos: datos, generador y componente UI",
      "Consolidación de 11 useState en InvoiceForm a un solo useFormState",
      "NotesCard con modo readOnly para páginas de detalle",
      "Renombrado de variables ambiguas (qc→queryClient, fl→forklift, etc.)",
    ],
  },
  {
    version: "3.5.3",
    date: "2026-02-28",
    type: "patch",
    title: "Corrección de facturación recurrente",
    description: "La primera factura recurrente ahora cubre correctamente el mes de inicio de la reserva.",
    changes: [
      "Primera factura ahora cubre el mes de inicio de la reserva en lugar de saltarlo",
      "Corrección en la lógica de last_billed_date para facturación automática",
    ],
  },
  {
    version: "3.5.2",
    date: "2026-02-28",
    type: "patch",
    title: "Corrección de cálculo de meses en rentas",
    description: "La fecha final ahora se trata como inclusiva para calcular correctamente la duración de periodos de renta.",
    changes: [
      "Fecha final tratada como inclusiva: periodos como 01/12 al 30/11 ahora calculan 12 meses exactos",
      "Ajuste en invoiceUtils para evitar cobros de un mes menos en rentas largas",
    ],
  },
  {
    version: "3.5.1",
    date: "2026-02-27",
    type: "patch",
    title: "Revertir acciones desde la Bitácora",
    description: "Al eliminar un registro de la bitácora, ahora puedes elegir entre solo borrar el registro o revertir la acción original en la base de datos.",
    changes: [
      "Nuevo diálogo con dos opciones: borrar solo de bitácora o revertir la acción",
      "Reversión atómica: INSERT se elimina, UPDATE restaura valores anteriores, DELETE re-inserta",
      "Validación de seguridad: solo admins con whitelist de tablas permitidas",
      "Información contextual sobre qué pasará al revertir cada tipo de acción",
    ],
  },
  {
    version: "3.5.0",
    date: "2026-02-27",
    type: "minor",
    title: "Eliminar registros de la Bitácora de Cambios",
    description: "Los administradores ahora pueden eliminar registros individuales de la bitácora de cambios (audit trail) con un diálogo de confirmación.",
    changes: [
      "Nuevo botón de eliminar en cada registro de la bitácora (solo visible para Admin)",
      "Diálogo de confirmación antes de borrar para evitar eliminaciones accidentales",
      "Notificación de éxito o error al eliminar un registro",
    ],
  },
  {
    version: "3.4.0",
    date: "2026-02-27",
    type: "minor",
    title: "Reporte de Utilización por Modelo",
    description: "Nuevo reporte que agrupa la utilización de la flota por modelo de equipo, facilitando decisiones de compra al identificar qué modelos tienen alta demanda.",
    changes: [
      "Nuevo reporte 'Utilización por Modelo' en la página de Reportes",
      "Gráfica de barras horizontales con colores por nivel de utilización (verde/amarillo/rojo)",
      "Tabla detallada con unidades, disponibles, rentados, días reservados y % de utilización",
      "Exportación a CSV del reporte",
      "Equipos vendidos o retirados se excluyen automáticamente del cálculo",
    ],
  },
  {
    version: "3.3.1",
    date: "2026-02-27",
    type: "patch",
    title: "Generación de manual restringida a Admin",
    description: "Solo el rol Admin puede generar nuevos manuales. Cada regeneración incrementa automáticamente la versión y se conservan las versiones anteriores.",
    changes: [
      "Solo el rol Admin puede generar y regenerar el manual de usuario",
      "Versión incremental automática (1.0 → 2.0 → 3.0) en cada generación",
      "Se conservan versiones anteriores del manual con selector de versión",
      "Política RLS actualizada para restringir escritura solo a admin",
    ],
  },
  {
    version: "3.3.0",
    date: "2026-02-26",
    type: "minor",
    title: "Manual de Usuario con IA",
    description: "Nueva sección de Ayuda con un manual de usuario completo generado por inteligencia artificial, con documentación detallada de cada módulo y workflows paso a paso.",
    changes: [
      "Nueva página /help con manual de usuario generado por IA",
      "18 secciones cubriendo todos los módulos de la app",
      "Workflows completos: flujo de renta, facturación recurrente, daños y mantenimiento",
      "Barra de búsqueda para filtrar contenido del manual",
      "Botón de regenerar manual disponible para administradores",
      "Accesible desde el sidebar para todos los roles",
    ],
  },
  {
    version: "3.2.0",
    date: "2026-02-26",
    type: "minor",
    title: "Editor de Plantilla de Contrato",
    description: "Los administradores ahora pueden editar el contenido de contratos, checklist y pagaré desde Configuración de Operaciones, sin modificar código.",
    changes: [
      "Nueva pestaña 'Plantilla de Contrato' en Configuración de Operaciones",
      "Editor de párrafo introductorio, declaraciones, cláusulas, checklist y pagaré",
      "Sistema de placeholders dinámicos ({arrendador}, {tarifa_mensual}, etc.)",
      "Generación de PDF lee la plantilla de la base de datos con fallback al contenido original",
      "Guía visual de placeholders disponibles en la interfaz de edición",
    ],
  },
  {
    version: "3.1.0",
    date: "2026-02-26",
    type: "minor",
    title: "Página de Changelog",
    description: "Nueva página dentro de la app que muestra el historial completo de cambios organizados por versión semántica.",
    changes: [
      "Historial de cambios con versionado semántico (MAJOR.MINOR.PATCH)",
      "Línea de tiempo visual con badges de color por tipo de cambio",
      "Filtros por tipo: Mayor, Menor y Parche",
      "Accesible desde el sidebar para todos los roles",
    ],
  },
  {
    version: "3.0.1",
    date: "2026-02-26",
    type: "patch",
    title: "Representante legal en clientes",
    description: "Se agregó el campo de representante legal en la ficha del cliente, y se integró automáticamente en el contrato y el pagaré.",
    changes: [
      "Nuevo campo 'Representante Legal' en el formulario de clientes",
      "El nombre del representante aparece automáticamente en el contrato PDF",
      "El pagaré (Anexo B) incluye al representante legal como firmante",
    ],
  },
  {
    version: "3.0.0",
    date: "2026-02-25",
    type: "major",
    title: "Contratos profesionales con anexos legales",
    description: "Rediseño completo del módulo de contratos con un machote profesional que incluye cláusulas legales, checklist de entrega y pagaré.",
    changes: [
      "8 cláusulas legales profesionales (objeto, vigencia, renta, obligaciones, etc.)",
      "Anexo A: Checklist de condiciones del equipo al momento de entrega",
      "Anexo B: Pagaré con datos del cliente y montos del contrato",
      "PDF multi-página generado con jsPDF",
      "Plantillas de contrato editables desde Configuración",
      "Testigos configurables por contrato",
    ],
  },
  {
    version: "2.5.1",
    date: "2026-02-24",
    type: "patch",
    title: "Actividad en español",
    description: "El feed de actividad ahora muestra todos los eventos traducidos al español en lugar de inglés.",
    changes: [
      "Traducciones completas del feed de actividad al español",
      "Tipos de evento y descripciones en lenguaje natural",
    ],
  },
  {
    version: "2.5.0",
    date: "2026-02-24",
    type: "minor",
    title: "Rol de auditor",
    description: "Nuevo rol 'auditor' que permite ver toda la información del sistema sin poder modificar nada.",
    changes: [
      "Rol 'auditor' con acceso de solo lectura a todas las secciones",
      "Visible en la gestión de usuarios para asignar a nuevos miembros",
    ],
  },
  {
    version: "2.4.1",
    date: "2026-02-23",
    type: "patch",
    title: "Corrección de permisos de perfil",
    description: "Se corrigió un problema donde los clientes del portal podían ver información de perfiles internos.",
    changes: [
      "Separación de permisos entre perfiles de clientes y personal interno",
      "Los clientes solo ven su propia información",
    ],
  },
  {
    version: "2.4.0",
    date: "2026-02-23",
    type: "minor",
    title: "Rol administrativo",
    description: "Nuevo rol 'administrativo' con permisos completos de operación, similar al dispatcher pero con acceso a configuración.",
    changes: [
      "Rol 'administrativo' con acceso completo a operaciones",
      "Acceso a configuración de empresa y operaciones",
      "Puede gestionar reservas, contratos, facturas y entregas",
    ],
  },
  {
    version: "2.3.1",
    date: "2026-02-23",
    type: "patch",
    title: "Mejoras al dashboard",
    description: "El panel principal ahora muestra información más precisa sobre la flota y su utilización.",
    changes: [
      "Nuevo estado 'vendido' para equipos retirados de la flota activa",
      "Gráfica de utilización semanal en el dashboard",
      "Los equipos retirados ya no se cuentan en las estadísticas de flota",
    ],
  },
  {
    version: "2.3.0",
    date: "2026-02-23",
    type: "minor",
    title: "Portal de clientes",
    description: "Los clientes ahora pueden iniciar sesión en su propio portal para ver sus rentas, facturas y contratos.",
    changes: [
      "Nuevo rol 'customer' para clientes con cuenta",
      "Pantalla de login dedicada para clientes en /portal/login",
      "Dashboard del portal con resumen de cuenta",
      "Vista de facturas y contratos desde la perspectiva del cliente",
      "Invitación de clientes por correo electrónico",
    ],
  },
  {
    version: "2.2.0",
    date: "2026-02-15",
    type: "minor",
    title: "Contratos, pagos y auditoría",
    description: "Se agregaron contratos de renta, registro de pagos parciales/totales, y auditoría detallada de cambios.",
    changes: [
      "Módulo de contratos con número consecutivo automático",
      "Registro de pagos con método, referencia y notas",
      "Auditoría detallada que registra qué campos cambiaron y sus valores anteriores",
      "Estado de factura se actualiza automáticamente al registrar pagos",
    ],
  },
  {
    version: "2.1.0",
    date: "2026-02-15",
    type: "minor",
    title: "Choferes, mecánicos y datos fiscales",
    description: "Nuevos catálogos de choferes y mecánicos, más integración con datos fiscales del SAT para facturación.",
    changes: [
      "Catálogo de choferes con licencia y datos de contacto",
      "Catálogo de mecánicos con especialización",
      "Configuración de datos fiscales de la empresa (RFC, razón social, régimen)",
      "Campos de CFDI en facturas (uso CFDI, forma de pago, método de pago)",
    ],
  },
  {
    version: "2.0.3",
    date: "2026-02-15",
    type: "patch",
    title: "Cancelación de reservas y validaciones",
    description: "Ahora se pueden cancelar reservas activas, y se validó que no haya equipos con nombres o series duplicadas.",
    changes: [
      "Botón de cancelar reserva con confirmación",
      "Validación de nombres únicos en equipos",
      "Validación de números de serie únicos",
    ],
  },
  {
    version: "2.0.2",
    date: "2026-02-14",
    type: "patch",
    title: "Optimización de base de datos",
    description: "Se agregaron índices en las tablas principales para mejorar la velocidad de las consultas.",
    changes: [
      "Índices de rendimiento en reservas, facturas, mantenimiento y más",
      "Mejora en tiempos de carga de listados grandes",
    ],
  },
  {
    version: "2.0.1",
    date: "2026-02-14",
    type: "patch",
    title: "Procedimientos atómicos",
    description: "Las operaciones críticas ahora se ejecutan como transacciones atómicas para evitar datos inconsistentes.",
    changes: [
      "Crear reserva: valida disponibilidad y cambia estado del equipo en una sola transacción",
      "Eliminar equipo: limpia dependencias automáticamente",
      "Completar inspección: cierra reserva y libera equipo de forma atómica",
    ],
  },
  {
    version: "2.0.0",
    date: "2026-02-14",
    type: "major",
    title: "Autenticación, roles y nuevos módulos",
    description: "Gran actualización que agrega sistema de usuarios con roles, cotizaciones, actividad y registro de daños.",
    changes: [
      "Sistema de autenticación con login y registro",
      "Roles de usuario: admin, dispatcher, mecánico",
      "Control de acceso por rol en todas las secciones",
      "Módulo de cotizaciones con número consecutivo",
      "Feed de actividad en tiempo real",
      "Registro de daños vinculado a equipos y reservas",
    ],
  },
  {
    version: "1.2.0",
    date: "2026-02-13",
    type: "minor",
    title: "Devoluciones, entregas y documentos",
    description: "Se completó el flujo operativo con inspecciones de devolución, programación de entregas y adjuntos.",
    changes: [
      "Inspecciones de devolución con checklist de condición",
      "Programación de entregas y recolecciones",
      "Documentos adjuntos en reservas, equipos y clientes",
    ],
  },
  {
    version: "1.1.0",
    date: "2026-02-13",
    type: "minor",
    title: "Clientes, mantenimiento y facturas",
    description: "Se agregaron los módulos de clientes, registro de mantenimiento, facturación y catálogo de modelos.",
    changes: [
      "Catálogo de clientes con datos de contacto",
      "Registro de mantenimiento por equipo",
      "Módulo de facturación con partidas y totales",
      "Catálogo de modelos de equipo con especificaciones por defecto",
    ],
  },
  {
    version: "1.0.0",
    date: "2026-02-12",
    type: "major",
    title: "Lanzamiento inicial",
    description: "Primera versión del sistema con los módulos básicos para gestionar una flota de montacargas en renta.",
    changes: [
      "Catálogo de equipos (montacargas) con estado y especificaciones",
      "Reservas con fechas de inicio y fin",
      "Calendario visual de disponibilidad",
      "Panel principal con estadísticas generales",
    ],
  },
];

export const CURRENT_VERSION = changelog[0].version;
