project_id = "zxefrzfaynnfwazqhwxp"

[functions.delete-user]
verify_jwt = false

[functions.parse-csf]
verify_jwt = false

[functions.generate-manual]
verify_jwt = false

[functions.generate-recurring-maintenance]
verify_jwt = false
