/**
 * Catálogo unificado de códigos de error para LiftGo.
 * Núcleo (transporte/DB) + dominio (operación). Mensajes en es-MX con
 * interpolación opcional `{var}`.
 */
export const ERROR_CODES = {
  // Núcleo
  VALIDATION_FAILED: "VALIDATION_FAILED",
  DB_PERMISSION_DENIED: "DB_PERMISSION_DENIED",
  DB_UNIQUE_VIOLATION: "DB_UNIQUE_VIOLATION",
  DB_FOREIGN_KEY: "DB_FOREIGN_KEY",
  NETWORK_ERROR: "NETWORK_ERROR",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  UNKNOWN: "UNKNOWN",
  // Dominio LiftGo
  BOOKING_OVERLAP: "BOOKING_OVERLAP",
  FORKLIFT_UNAVAILABLE: "FORKLIFT_UNAVAILABLE",
  MAINTENANCE_BLOCK: "MAINTENANCE_BLOCK",
  QUOTE_NOT_EDITABLE: "QUOTE_NOT_EDITABLE",
  QUOTE_GENERIC_CUSTOMER: "QUOTE_GENERIC_CUSTOMER",
  INVOICE_ALREADY_PAID: "INVOICE_ALREADY_PAID",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",
  CFDI_FACTURAPI_ERROR: "CFDI_FACTURAPI_ERROR",
  MODELS_REQUIRED: "MODELS_REQUIRED",
  PAYMENT_EXCEEDS_BALANCE: "PAYMENT_EXCEEDS_BALANCE",
  RECURRING_BILLING_LOCKED: "RECURRING_BILLING_LOCKED",
  ROLE_FORBIDDEN: "ROLE_FORBIDDEN",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];




