/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MainRouteImport } from './routes/_main'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as MainIndexRouteImport } from './routes/_main/index'
import { Route as MainSplatRouteImport } from './routes/_main/$'
import { Route as MainAccountsPayableRouteImport } from './routes/_main/accounts-payable'
import { Route as MainActivityRouteImport } from './routes/_main/activity'
import { Route as MainAuditRouteImport } from './routes/_main/audit'
import { Route as MainAvailabilityRouteImport } from './routes/_main/availability'
import { Route as MainBankReconciliationRouteImport } from './routes/_main/bank-reconciliation'
import { Route as MainCalendarRouteImport } from './routes/_main/calendar'
import { Route as MainCashFlowRouteImport } from './routes/_main/cash-flow'
import { Route as MainChangelogRouteImport } from './routes/_main/changelog'
import { Route as MainConciliacionRouteImport } from './routes/_main/conciliacion'
import { Route as MainCuentasBancariasRouteImport } from './routes/_main/cuentas-bancarias'
import { Route as MainDamageRouteImport } from './routes/_main/damage'
import { Route as MainExpensesRouteImport } from './routes/_main/expenses'
import { Route as MainFeedbackRouteImport } from './routes/_main/feedback'
import { Route as MainFlujoDeCajaRouteImport } from './routes/_main/flujo-de-caja'
import { Route as MainHelpRouteImport } from './routes/_main/help'
import { Route as MainIncomeStatementRouteImport } from './routes/_main/income-statement'
import { Route as MainInventoryRouteImport } from './routes/_main/inventory'
import { Route as MainLeaderboardRouteImport } from './routes/_main/leaderboard'
import { Route as MainLoginRouteImport } from './routes/_main/login'
import { Route as MainMaintenanceRouteImport } from './routes/_main/maintenance'
import { Route as MainMisReportesRouteImport } from './routes/_main/mis-reportes'
import { Route as MainMrrRouteImport } from './routes/_main/mrr'
import { Route as MainPaymentsRouteImport } from './routes/_main/payments'
import { Route as MainProspectsRouteImport } from './routes/_main/prospects'
import { Route as MainReportsRouteImport } from './routes/_main/reports'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as MainBookingsIndexRouteImport } from './routes/_main/bookings.index'
import { Route as MainBookingsIdRouteImport } from './routes/_main/bookings.$id'
import { Route as MainBookingsNewRouteImport } from './routes/_main/bookings.new'
import { Route as MainConciliacionBancariaIndexRouteImport } from './routes/_main/conciliacion-bancaria.index'
import { Route as MainConciliacionBancariaHistorialRouteImport } from './routes/_main/conciliacion-bancaria.historial'
import { Route as MainContractsIndexRouteImport } from './routes/_main/contracts.index'
import { Route as MainContractsNewRouteImport } from './routes/_main/contracts.new'
import { Route as MainCrmIndexRouteImport } from './routes/_main/crm.index'
import { Route as MainCrmCerradosRouteImport } from './routes/_main/crm.cerrados'
import { Route as MainCuentasPorPagarIndexRouteImport } from './routes/_main/cuentas-por-pagar.index'
import { Route as MainCuentasPorPagarAntiguedadRouteImport } from './routes/_main/cuentas-por-pagar.antiguedad'
import { Route as MainCustomersIndexRouteImport } from './routes/_main/customers.index'
import { Route as MainCustomersIdRouteImport } from './routes/_main/customers.$id'
import { Route as MainCustomersNewRouteImport } from './routes/_main/customers.new'
import { Route as MainCustomersValidacionSatRouteImport } from './routes/_main/customers.validacion-sat'
import { Route as MainDeliveriesIndexRouteImport } from './routes/_main/deliveries.index'
import { Route as MainDeliveriesIdRouteImport } from './routes/_main/deliveries.$id'
import { Route as MainFleetIndexRouteImport } from './routes/_main/fleet.index'
import { Route as MainFleetNewRouteImport } from './routes/_main/fleet.new'
import { Route as MainInvoicesIndexRouteImport } from './routes/_main/invoices.index'
import { Route as MainInvoicesNewRouteImport } from './routes/_main/invoices.new'
import { Route as MainInvoicesReconciliationRouteImport } from './routes/_main/invoices.reconciliation'
import { Route as MainQuotesIndexRouteImport } from './routes/_main/quotes.index'
import { Route as MainQuotesNewRouteImport } from './routes/_main/quotes.new'
import { Route as MainReturnsIndexRouteImport } from './routes/_main/returns.index'
import { Route as MainReturnsIdRouteImport } from './routes/_main/returns.$id'
import { Route as MainReturnsPendingRouteImport } from './routes/_main/returns.pending'
import { Route as MainSettingsIndexRouteImport } from './routes/_main/settings.index'
import { Route as MainSettingsCompanyRouteImport } from './routes/_main/settings.company'
import { Route as MainSettingsOperationsRouteImport } from './routes/_main/settings.operations'
import { Route as MainSuppliersIndexRouteImport } from './routes/_main/suppliers.index'
import { Route as MainSuppliersIdRouteImport } from './routes/_main/suppliers.$id'
import { Route as MainUsersIndexRouteImport } from './routes/_main/users.index'
import { Route as MainUsersPermissionsRouteImport } from './routes/_main/users.permissions'
import { Route as PortalPortalIndexRouteImport } from './routes/_portal/portal.index'
import { Route as PortalPortalSplatRouteImport } from './routes/_portal/portal.$'
import { Route as PortalPortalContractsRouteImport } from './routes/_portal/portal.contracts'
import { Route as PortalPortalEstadoCuentaRouteImport } from './routes/_portal/portal.estado-cuenta'
import { Route as PortalPortalLeaderboardRouteImport } from './routes/_portal/portal.leaderboard'
import { Route as PortalPortalMisReportesRouteImport } from './routes/_portal/portal.mis-reportes'
import { Route as PortalPortalRentalsRouteImport } from './routes/_portal/portal.rentals'
import { Route as MainContractsIdIndexRouteImport } from './routes/_main/contracts.$id.index'
import { Route as MainContractsIdEditRouteImport } from './routes/_main/contracts.$id.edit'
import { Route as MainFleetIdIndexRouteImport } from './routes/_main/fleet.$id.index'
import { Route as MainFleetIdEditRouteImport } from './routes/_main/fleet.$id.edit'
import { Route as MainInvoicesIdIndexRouteImport } from './routes/_main/invoices.$id.index'
import { Route as MainInvoicesIdEditRouteImport } from './routes/_main/invoices.$id.edit'
import { Route as MainQuotesIdIndexRouteImport } from './routes/_main/quotes.$id.index'
import { Route as MainQuotesIdEditRouteImport } from './routes/_main/quotes.$id.edit'
import { Route as PortalPortalInvoicesIndexRouteImport } from './routes/_portal/portal.invoices.index'
import { Route as PortalPortalQuotesIndexRouteImport } from './routes/_portal/portal.quotes.index'
import { Route as PortalPortalQuotesIdRouteImport } from './routes/_portal/portal.quotes.$id'
import { Route as PortalPortalInvoicesIdIndexRouteImport } from './routes/_portal/portal.invoices.$id.index'
import { Route as PortalPortalInvoicesIdPagoRouteImport } from './routes/_portal/portal.invoices.$id.pago'

const MainRoute = MainRouteImport.update({
  id: '/_main',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const MainIndexRoute = MainIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MainRoute,
} as any)
const MainSplatRoute = MainSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => MainRoute,
} as any)
const MainAccountsPayableRoute = MainAccountsPayableRouteImport.update({
  id: '/accounts-payable',
  path: '/accounts-payable',
  getParentRoute: () => MainRoute,
} as any)
const MainActivityRoute = MainActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => MainRoute,
} as any)
const MainAuditRoute = MainAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => MainRoute,
} as any)
const MainAvailabilityRoute = MainAvailabilityRouteImport.update({
  id: '/availability',
  path: '/availability',
  getParentRoute: () => MainRoute,
} as any)
const MainBankReconciliationRoute = MainBankReconciliationRouteImport.update({
  id: '/bank-reconciliation',
  path: '/bank-reconciliation',
  getParentRoute: () => MainRoute,
} as any)
const MainCalendarRoute = MainCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => MainRoute,
} as any)
const MainCashFlowRoute = MainCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => MainRoute,
} as any)
const MainChangelogRoute = MainChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => MainRoute,
} as any)
const MainConciliacionRoute = MainConciliacionRouteImport.update({
  id: '/conciliacion',
  path: '/conciliacion',
  getParentRoute: () => MainRoute,
} as any)
const MainCuentasBancariasRoute = MainCuentasBancariasRouteImport.update({
  id: '/cuentas-bancarias',
  path: '/cuentas-bancarias',
  getParentRoute: () => MainRoute,
} as any)
const MainDamageRoute = MainDamageRouteImport.update({
  id: '/damage',
  path: '/damage',
  getParentRoute: () => MainRoute,
} as any)
const MainExpensesRoute = MainExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => MainRoute,
} as any)
const MainFeedbackRoute = MainFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => MainRoute,
} as any)
const MainFlujoDeCajaRoute = MainFlujoDeCajaRouteImport.update({
  id: '/flujo-de-caja',
  path: '/flujo-de-caja',
  getParentRoute: () => MainRoute,
} as any)
const MainHelpRoute = MainHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => MainRoute,
} as any)
const MainIncomeStatementRoute = MainIncomeStatementRouteImport.update({
  id: '/income-statement',
  path: '/income-statement',
  getParentRoute: () => MainRoute,
} as any)
const MainInventoryRoute = MainInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => MainRoute,
} as any)
const MainLeaderboardRoute = MainLeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => MainRoute,
} as any)
const MainLoginRoute = MainLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MainRoute,
} as any)
const MainMaintenanceRoute = MainMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => MainRoute,
} as any)
const MainMisReportesRoute = MainMisReportesRouteImport.update({
  id: '/mis-reportes',
  path: '/mis-reportes',
  getParentRoute: () => MainRoute,
} as any)
const MainMrrRoute = MainMrrRouteImport.update({
  id: '/mrr',
  path: '/mrr',
  getParentRoute: () => MainRoute,
} as any)
const MainPaymentsRoute = MainPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => MainRoute,
} as any)
const MainProspectsRoute = MainProspectsRouteImport.update({
  id: '/prospects',
  path: '/prospects',
  getParentRoute: () => MainRoute,
} as any)
const MainReportsRoute = MainReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => MainRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/portal/login',
  path: '/portal/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MainBookingsIndexRoute = MainBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingsIdRoute = MainBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainBookingsNewRoute = MainBookingsNewRouteImport.update({
  id: '/bookings/new',
  path: '/bookings/new',
  getParentRoute: () => MainRoute,
} as any)
const MainConciliacionBancariaIndexRoute =
  MainConciliacionBancariaIndexRouteImport.update({
    id: '/conciliacion-bancaria/',
    path: '/conciliacion-bancaria/',
    getParentRoute: () => MainRoute,
  } as any)
const MainConciliacionBancariaHistorialRoute =
  MainConciliacionBancariaHistorialRouteImport.update({
    id: '/conciliacion-bancaria/historial',
    path: '/conciliacion-bancaria/historial',
    getParentRoute: () => MainRoute,
  } as any)
const MainContractsIndexRoute = MainContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => MainRoute,
} as any)
const MainContractsNewRoute = MainContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => MainRoute,
} as any)
const MainCrmIndexRoute = MainCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => MainRoute,
} as any)
const MainCrmCerradosRoute = MainCrmCerradosRouteImport.update({
  id: '/crm/cerrados',
  path: '/crm/cerrados',
  getParentRoute: () => MainRoute,
} as any)
const MainCuentasPorPagarIndexRoute =
  MainCuentasPorPagarIndexRouteImport.update({
    id: '/cuentas-por-pagar/',
    path: '/cuentas-por-pagar/',
    getParentRoute: () => MainRoute,
  } as any)
const MainCuentasPorPagarAntiguedadRoute =
  MainCuentasPorPagarAntiguedadRouteImport.update({
    id: '/cuentas-por-pagar/antiguedad',
    path: '/cuentas-por-pagar/antiguedad',
    getParentRoute: () => MainRoute,
  } as any)
const MainCustomersIndexRoute = MainCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => MainRoute,
} as any)
const MainCustomersIdRoute = MainCustomersIdRouteImport.update({
  id: '/customers/$id',
  path: '/customers/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainCustomersNewRoute = MainCustomersNewRouteImport.update({
  id: '/customers/new',
  path: '/customers/new',
  getParentRoute: () => MainRoute,
} as any)
const MainCustomersValidacionSatRoute =
  MainCustomersValidacionSatRouteImport.update({
    id: '/customers/validacion-sat',
    path: '/customers/validacion-sat',
    getParentRoute: () => MainRoute,
  } as any)
const MainDeliveriesIndexRoute = MainDeliveriesIndexRouteImport.update({
  id: '/deliveries/',
  path: '/deliveries/',
  getParentRoute: () => MainRoute,
} as any)
const MainDeliveriesIdRoute = MainDeliveriesIdRouteImport.update({
  id: '/deliveries/$id',
  path: '/deliveries/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainFleetIndexRoute = MainFleetIndexRouteImport.update({
  id: '/fleet/',
  path: '/fleet/',
  getParentRoute: () => MainRoute,
} as any)
const MainFleetNewRoute = MainFleetNewRouteImport.update({
  id: '/fleet/new',
  path: '/fleet/new',
  getParentRoute: () => MainRoute,
} as any)
const MainInvoicesIndexRoute = MainInvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => MainRoute,
} as any)
const MainInvoicesNewRoute = MainInvoicesNewRouteImport.update({
  id: '/invoices/new',
  path: '/invoices/new',
  getParentRoute: () => MainRoute,
} as any)
const MainInvoicesReconciliationRoute =
  MainInvoicesReconciliationRouteImport.update({
    id: '/invoices/reconciliation',
    path: '/invoices/reconciliation',
    getParentRoute: () => MainRoute,
  } as any)
const MainQuotesIndexRoute = MainQuotesIndexRouteImport.update({
  id: '/quotes/',
  path: '/quotes/',
  getParentRoute: () => MainRoute,
} as any)
const MainQuotesNewRoute = MainQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => MainRoute,
} as any)
const MainReturnsIndexRoute = MainReturnsIndexRouteImport.update({
  id: '/returns/',
  path: '/returns/',
  getParentRoute: () => MainRoute,
} as any)
const MainReturnsIdRoute = MainReturnsIdRouteImport.update({
  id: '/returns/$id',
  path: '/returns/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainReturnsPendingRoute = MainReturnsPendingRouteImport.update({
  id: '/returns/pending',
  path: '/returns/pending',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsIndexRoute = MainSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsCompanyRoute = MainSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => MainRoute,
} as any)
const MainSettingsOperationsRoute = MainSettingsOperationsRouteImport.update({
  id: '/settings/operations',
  path: '/settings/operations',
  getParentRoute: () => MainRoute,
} as any)
const MainSuppliersIndexRoute = MainSuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => MainRoute,
} as any)
const MainSuppliersIdRoute = MainSuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => MainRoute,
} as any)
const MainUsersIndexRoute = MainUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => MainRoute,
} as any)
const MainUsersPermissionsRoute = MainUsersPermissionsRouteImport.update({
  id: '/users/permissions',
  path: '/users/permissions',
  getParentRoute: () => MainRoute,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/portal/',
  path: '/portal/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalSplatRoute = PortalPortalSplatRouteImport.update({
  id: '/portal/$',
  path: '/portal/$',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalContractsRoute = PortalPortalContractsRouteImport.update({
  id: '/portal/contracts',
  path: '/portal/contracts',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalEstadoCuentaRoute =
  PortalPortalEstadoCuentaRouteImport.update({
    id: '/portal/estado-cuenta',
    path: '/portal/estado-cuenta',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalLeaderboardRoute = PortalPortalLeaderboardRouteImport.update({
  id: '/portal/leaderboard',
  path: '/portal/leaderboard',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalMisReportesRoute = PortalPortalMisReportesRouteImport.update({
  id: '/portal/mis-reportes',
  path: '/portal/mis-reportes',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalRentalsRoute = PortalPortalRentalsRouteImport.update({
  id: '/portal/rentals',
  path: '/portal/rentals',
  getParentRoute: () => PortalRoute,
} as any)
const MainContractsIdIndexRoute = MainContractsIdIndexRouteImport.update({
  id: '/contracts/$id/',
  path: '/contracts/$id/',
  getParentRoute: () => MainRoute,
} as any)
const MainContractsIdEditRoute = MainContractsIdEditRouteImport.update({
  id: '/contracts/$id/edit',
  path: '/contracts/$id/edit',
  getParentRoute: () => MainRoute,
} as any)
const MainFleetIdIndexRoute = MainFleetIdIndexRouteImport.update({
  id: '/fleet/$id/',
  path: '/fleet/$id/',
  getParentRoute: () => MainRoute,
} as any)
const MainFleetIdEditRoute = MainFleetIdEditRouteImport.update({
  id: '/fleet/$id/edit',
  path: '/fleet/$id/edit',
  getParentRoute: () => MainRoute,
} as any)
const MainInvoicesIdIndexRoute = MainInvoicesIdIndexRouteImport.update({
  id: '/invoices/$id/',
  path: '/invoices/$id/',
  getParentRoute: () => MainRoute,
} as any)
const MainInvoicesIdEditRoute = MainInvoicesIdEditRouteImport.update({
  id: '/invoices/$id/edit',
  path: '/invoices/$id/edit',
  getParentRoute: () => MainRoute,
} as any)
const MainQuotesIdIndexRoute = MainQuotesIdIndexRouteImport.update({
  id: '/quotes/$id/',
  path: '/quotes/$id/',
  getParentRoute: () => MainRoute,
} as any)
const MainQuotesIdEditRoute = MainQuotesIdEditRouteImport.update({
  id: '/quotes/$id/edit',
  path: '/quotes/$id/edit',
  getParentRoute: () => MainRoute,
} as any)
const PortalPortalInvoicesIndexRoute =
  PortalPortalInvoicesIndexRouteImport.update({
    id: '/portal/invoices/',
    path: '/portal/invoices/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalQuotesIndexRoute = PortalPortalQuotesIndexRouteImport.update({
  id: '/portal/quotes/',
  path: '/portal/quotes/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalQuotesIdRoute = PortalPortalQuotesIdRouteImport.update({
  id: '/portal/quotes/$id',
  path: '/portal/quotes/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalPortalInvoicesIdIndexRoute =
  PortalPortalInvoicesIdIndexRouteImport.update({
    id: '/portal/invoices/$id/',
    path: '/portal/invoices/$id/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalPortalInvoicesIdPagoRoute =
  PortalPortalInvoicesIdPagoRouteImport.update({
    id: '/portal/invoices/$id/pago',
    path: '/portal/invoices/$id/pago',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MainIndexRoute
  '/$': typeof MainSplatRoute
  '/accounts-payable': typeof MainAccountsPayableRoute
  '/activity': typeof MainActivityRoute
  '/audit': typeof MainAuditRoute
  '/availability': typeof MainAvailabilityRoute
  '/bank-reconciliation': typeof MainBankReconciliationRoute
  '/calendar': typeof MainCalendarRoute
  '/cash-flow': typeof MainCashFlowRoute
  '/changelog': typeof MainChangelogRoute
  '/conciliacion': typeof MainConciliacionRoute
  '/cuentas-bancarias': typeof MainCuentasBancariasRoute
  '/damage': typeof MainDamageRoute
  '/expenses': typeof MainExpensesRoute
  '/feedback': typeof MainFeedbackRoute
  '/flujo-de-caja': typeof MainFlujoDeCajaRoute
  '/help': typeof MainHelpRoute
  '/income-statement': typeof MainIncomeStatementRoute
  '/inventory': typeof MainInventoryRoute
  '/leaderboard': typeof MainLeaderboardRoute
  '/login': typeof MainLoginRoute
  '/maintenance': typeof MainMaintenanceRoute
  '/mis-reportes': typeof MainMisReportesRoute
  '/mrr': typeof MainMrrRoute
  '/payments': typeof MainPaymentsRoute
  '/prospects': typeof MainProspectsRoute
  '/reports': typeof MainReportsRoute
  '/portal/login': typeof PortalLoginRoute
  '/bookings/$id': typeof MainBookingsIdRoute
  '/bookings/new': typeof MainBookingsNewRoute
  '/conciliacion-bancaria/historial': typeof MainConciliacionBancariaHistorialRoute
  '/contracts/new': typeof MainContractsNewRoute
  '/crm/cerrados': typeof MainCrmCerradosRoute
  '/cuentas-por-pagar/antiguedad': typeof MainCuentasPorPagarAntiguedadRoute
  '/customers/$id': typeof MainCustomersIdRoute
  '/customers/new': typeof MainCustomersNewRoute
  '/customers/validacion-sat': typeof MainCustomersValidacionSatRoute
  '/deliveries/$id': typeof MainDeliveriesIdRoute
  '/fleet/new': typeof MainFleetNewRoute
  '/invoices/new': typeof MainInvoicesNewRoute
  '/invoices/reconciliation': typeof MainInvoicesReconciliationRoute
  '/quotes/new': typeof MainQuotesNewRoute
  '/returns/$id': typeof MainReturnsIdRoute
  '/returns/pending': typeof MainReturnsPendingRoute
  '/settings/company': typeof MainSettingsCompanyRoute
  '/settings/operations': typeof MainSettingsOperationsRoute
  '/suppliers/$id': typeof MainSuppliersIdRoute
  '/users/permissions': typeof MainUsersPermissionsRoute
  '/portal/$': typeof PortalPortalSplatRoute
  '/portal/contracts': typeof PortalPortalContractsRoute
  '/portal/estado-cuenta': typeof PortalPortalEstadoCuentaRoute
  '/portal/leaderboard': typeof PortalPortalLeaderboardRoute
  '/portal/mis-reportes': typeof PortalPortalMisReportesRoute
  '/portal/rentals': typeof PortalPortalRentalsRoute
  '/bookings/': typeof MainBookingsIndexRoute
  '/conciliacion-bancaria/': typeof MainConciliacionBancariaIndexRoute
  '/contracts/': typeof MainContractsIndexRoute
  '/crm/': typeof MainCrmIndexRoute
  '/cuentas-por-pagar/': typeof MainCuentasPorPagarIndexRoute
  '/customers/': typeof MainCustomersIndexRoute
  '/deliveries/': typeof MainDeliveriesIndexRoute
  '/fleet/': typeof MainFleetIndexRoute
  '/invoices/': typeof MainInvoicesIndexRoute
  '/quotes/': typeof MainQuotesIndexRoute
  '/returns/': typeof MainReturnsIndexRoute
  '/settings/': typeof MainSettingsIndexRoute
  '/suppliers/': typeof MainSuppliersIndexRoute
  '/users/': typeof MainUsersIndexRoute
  '/portal/': typeof PortalPortalIndexRoute
  '/contracts/$id/edit': typeof MainContractsIdEditRoute
  '/fleet/$id/edit': typeof MainFleetIdEditRoute
  '/invoices/$id/edit': typeof MainInvoicesIdEditRoute
  '/quotes/$id/edit': typeof MainQuotesIdEditRoute
  '/portal/quotes/$id': typeof PortalPortalQuotesIdRoute
  '/contracts/$id/': typeof MainContractsIdIndexRoute
  '/fleet/$id/': typeof MainFleetIdIndexRoute
  '/invoices/$id/': typeof MainInvoicesIdIndexRoute
  '/quotes/$id/': typeof MainQuotesIdIndexRoute
  '/portal/invoices/': typeof PortalPortalInvoicesIndexRoute
  '/portal/quotes/': typeof PortalPortalQuotesIndexRoute
  '/portal/invoices/$id/pago': typeof PortalPortalInvoicesIdPagoRoute
  '/portal/invoices/$id/': typeof PortalPortalInvoicesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MainIndexRoute
  '/$': typeof MainSplatRoute
  '/accounts-payable': typeof MainAccountsPayableRoute
  '/activity': typeof MainActivityRoute
  '/audit': typeof MainAuditRoute
  '/availability': typeof MainAvailabilityRoute
  '/bank-reconciliation': typeof MainBankReconciliationRoute
  '/calendar': typeof MainCalendarRoute
  '/cash-flow': typeof MainCashFlowRoute
  '/changelog': typeof MainChangelogRoute
  '/conciliacion': typeof MainConciliacionRoute
  '/cuentas-bancarias': typeof MainCuentasBancariasRoute
  '/damage': typeof MainDamageRoute
  '/expenses': typeof MainExpensesRoute
  '/feedback': typeof MainFeedbackRoute
  '/flujo-de-caja': typeof MainFlujoDeCajaRoute
  '/help': typeof MainHelpRoute
  '/income-statement': typeof MainIncomeStatementRoute
  '/inventory': typeof MainInventoryRoute
  '/leaderboard': typeof MainLeaderboardRoute
  '/login': typeof MainLoginRoute
  '/maintenance': typeof MainMaintenanceRoute
  '/mis-reportes': typeof MainMisReportesRoute
  '/mrr': typeof MainMrrRoute
  '/payments': typeof MainPaymentsRoute
  '/prospects': typeof MainProspectsRoute
  '/reports': typeof MainReportsRoute
  '/portal/login': typeof PortalLoginRoute
  '/bookings/$id': typeof MainBookingsIdRoute
  '/bookings/new': typeof MainBookingsNewRoute
  '/conciliacion-bancaria/historial': typeof MainConciliacionBancariaHistorialRoute
  '/contracts/new': typeof MainContractsNewRoute
  '/crm/cerrados': typeof MainCrmCerradosRoute
  '/cuentas-por-pagar/antiguedad': typeof MainCuentasPorPagarAntiguedadRoute
  '/customers/$id': typeof MainCustomersIdRoute
  '/customers/new': typeof MainCustomersNewRoute
  '/customers/validacion-sat': typeof MainCustomersValidacionSatRoute
  '/deliveries/$id': typeof MainDeliveriesIdRoute
  '/fleet/new': typeof MainFleetNewRoute
  '/invoices/new': typeof MainInvoicesNewRoute
  '/invoices/reconciliation': typeof MainInvoicesReconciliationRoute
  '/quotes/new': typeof MainQuotesNewRoute
  '/returns/$id': typeof MainReturnsIdRoute
  '/returns/pending': typeof MainReturnsPendingRoute
  '/settings/company': typeof MainSettingsCompanyRoute
  '/settings/operations': typeof MainSettingsOperationsRoute
  '/suppliers/$id': typeof MainSuppliersIdRoute
  '/users/permissions': typeof MainUsersPermissionsRoute
  '/portal/$': typeof PortalPortalSplatRoute
  '/portal/contracts': typeof PortalPortalContractsRoute
  '/portal/estado-cuenta': typeof PortalPortalEstadoCuentaRoute
  '/portal/leaderboard': typeof PortalPortalLeaderboardRoute
  '/portal/mis-reportes': typeof PortalPortalMisReportesRoute
  '/portal/rentals': typeof PortalPortalRentalsRoute
  '/bookings': typeof MainBookingsIndexRoute
  '/conciliacion-bancaria': typeof MainConciliacionBancariaIndexRoute
  '/contracts': typeof MainContractsIndexRoute
  '/crm': typeof MainCrmIndexRoute
  '/cuentas-por-pagar': typeof MainCuentasPorPagarIndexRoute
  '/customers': typeof MainCustomersIndexRoute
  '/deliveries': typeof MainDeliveriesIndexRoute
  '/fleet': typeof MainFleetIndexRoute
  '/invoices': typeof MainInvoicesIndexRoute
  '/quotes': typeof MainQuotesIndexRoute
  '/returns': typeof MainReturnsIndexRoute
  '/settings': typeof MainSettingsIndexRoute
  '/suppliers': typeof MainSuppliersIndexRoute
  '/users': typeof MainUsersIndexRoute
  '/portal': typeof PortalPortalIndexRoute
  '/contracts/$id/edit': typeof MainContractsIdEditRoute
  '/fleet/$id/edit': typeof MainFleetIdEditRoute
  '/invoices/$id/edit': typeof MainInvoicesIdEditRoute
  '/quotes/$id/edit': typeof MainQuotesIdEditRoute
  '/portal/quotes/$id': typeof PortalPortalQuotesIdRoute
  '/contracts/$id': typeof MainContractsIdIndexRoute
  '/fleet/$id': typeof MainFleetIdIndexRoute
  '/invoices/$id': typeof MainInvoicesIdIndexRoute
  '/quotes/$id': typeof MainQuotesIdIndexRoute
  '/portal/invoices': typeof PortalPortalInvoicesIndexRoute
  '/portal/quotes': typeof PortalPortalQuotesIndexRoute
  '/portal/invoices/$id/pago': typeof PortalPortalInvoicesIdPagoRoute
  '/portal/invoices/$id': typeof PortalPortalInvoicesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_main': typeof MainRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/_main/$': typeof MainSplatRoute
  '/_main/accounts-payable': typeof MainAccountsPayableRoute
  '/_main/activity': typeof MainActivityRoute
  '/_main/audit': typeof MainAuditRoute
  '/_main/availability': typeof MainAvailabilityRoute
  '/_main/bank-reconciliation': typeof MainBankReconciliationRoute
  '/_main/calendar': typeof MainCalendarRoute
  '/_main/cash-flow': typeof MainCashFlowRoute
  '/_main/changelog': typeof MainChangelogRoute
  '/_main/conciliacion': typeof MainConciliacionRoute
  '/_main/cuentas-bancarias': typeof MainCuentasBancariasRoute
  '/_main/damage': typeof MainDamageRoute
  '/_main/expenses': typeof MainExpensesRoute
  '/_main/feedback': typeof MainFeedbackRoute
  '/_main/flujo-de-caja': typeof MainFlujoDeCajaRoute
  '/_main/help': typeof MainHelpRoute
  '/_main/income-statement': typeof MainIncomeStatementRoute
  '/_main/inventory': typeof MainInventoryRoute
  '/_main/leaderboard': typeof MainLeaderboardRoute
  '/_main/login': typeof MainLoginRoute
  '/_main/maintenance': typeof MainMaintenanceRoute
  '/_main/mis-reportes': typeof MainMisReportesRoute
  '/_main/mrr': typeof MainMrrRoute
  '/_main/payments': typeof MainPaymentsRoute
  '/_main/prospects': typeof MainProspectsRoute
  '/_main/reports': typeof MainReportsRoute
  '/portal/login': typeof PortalLoginRoute
  '/_main/': typeof MainIndexRoute
  '/_main/bookings/$id': typeof MainBookingsIdRoute
  '/_main/bookings/new': typeof MainBookingsNewRoute
  '/_main/conciliacion-bancaria/historial': typeof MainConciliacionBancariaHistorialRoute
  '/_main/contracts/new': typeof MainContractsNewRoute
  '/_main/crm/cerrados': typeof MainCrmCerradosRoute
  '/_main/cuentas-por-pagar/antiguedad': typeof MainCuentasPorPagarAntiguedadRoute
  '/_main/customers/$id': typeof MainCustomersIdRoute
  '/_main/customers/new': typeof MainCustomersNewRoute
  '/_main/customers/validacion-sat': typeof MainCustomersValidacionSatRoute
  '/_main/deliveries/$id': typeof MainDeliveriesIdRoute
  '/_main/fleet/new': typeof MainFleetNewRoute
  '/_main/invoices/new': typeof MainInvoicesNewRoute
  '/_main/invoices/reconciliation': typeof MainInvoicesReconciliationRoute
  '/_main/quotes/new': typeof MainQuotesNewRoute
  '/_main/returns/$id': typeof MainReturnsIdRoute
  '/_main/returns/pending': typeof MainReturnsPendingRoute
  '/_main/settings/company': typeof MainSettingsCompanyRoute
  '/_main/settings/operations': typeof MainSettingsOperationsRoute
  '/_main/suppliers/$id': typeof MainSuppliersIdRoute
  '/_main/users/permissions': typeof MainUsersPermissionsRoute
  '/_portal/portal/$': typeof PortalPortalSplatRoute
  '/_portal/portal/contracts': typeof PortalPortalContractsRoute
  '/_portal/portal/estado-cuenta': typeof PortalPortalEstadoCuentaRoute
  '/_portal/portal/leaderboard': typeof PortalPortalLeaderboardRoute
  '/_portal/portal/mis-reportes': typeof PortalPortalMisReportesRoute
  '/_portal/portal/rentals': typeof PortalPortalRentalsRoute
  '/_main/bookings/': typeof MainBookingsIndexRoute
  '/_main/conciliacion-bancaria/': typeof MainConciliacionBancariaIndexRoute
  '/_main/contracts/': typeof MainContractsIndexRoute
  '/_main/crm/': typeof MainCrmIndexRoute
  '/_main/cuentas-por-pagar/': typeof MainCuentasPorPagarIndexRoute
  '/_main/customers/': typeof MainCustomersIndexRoute
  '/_main/deliveries/': typeof MainDeliveriesIndexRoute
  '/_main/fleet/': typeof MainFleetIndexRoute
  '/_main/invoices/': typeof MainInvoicesIndexRoute
  '/_main/quotes/': typeof MainQuotesIndexRoute
  '/_main/returns/': typeof MainReturnsIndexRoute
  '/_main/settings/': typeof MainSettingsIndexRoute
  '/_main/suppliers/': typeof MainSuppliersIndexRoute
  '/_main/users/': typeof MainUsersIndexRoute
  '/_portal/portal/': typeof PortalPortalIndexRoute
  '/_main/contracts/$id/edit': typeof MainContractsIdEditRoute
  '/_main/fleet/$id/edit': typeof MainFleetIdEditRoute
  '/_main/invoices/$id/edit': typeof MainInvoicesIdEditRoute
  '/_main/quotes/$id/edit': typeof MainQuotesIdEditRoute
  '/_portal/portal/quotes/$id': typeof PortalPortalQuotesIdRoute
  '/_main/contracts/$id/': typeof MainContractsIdIndexRoute
  '/_main/fleet/$id/': typeof MainFleetIdIndexRoute
  '/_main/invoices/$id/': typeof MainInvoicesIdIndexRoute
  '/_main/quotes/$id/': typeof MainQuotesIdIndexRoute
  '/_portal/portal/invoices/': typeof PortalPortalInvoicesIndexRoute
  '/_portal/portal/quotes/': typeof PortalPortalQuotesIndexRoute
  '/_portal/portal/invoices/$id/pago': typeof PortalPortalInvoicesIdPagoRoute
  '/_portal/portal/invoices/$id/': typeof PortalPortalInvoicesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/accounts-payable'
    | '/activity'
    | '/audit'
    | '/availability'
    | '/bank-reconciliation'
    | '/calendar'
    | '/cash-flow'
    | '/changelog'
    | '/conciliacion'
    | '/cuentas-bancarias'
    | '/damage'
    | '/expenses'
    | '/feedback'
    | '/flujo-de-caja'
    | '/help'
    | '/income-statement'
    | '/inventory'
    | '/leaderboard'
    | '/login'
    | '/maintenance'
    | '/mis-reportes'
    | '/mrr'
    | '/payments'
    | '/prospects'
    | '/reports'
    | '/portal/login'
    | '/bookings/$id'
    | '/bookings/new'
    | '/conciliacion-bancaria/historial'
    | '/contracts/new'
    | '/crm/cerrados'
    | '/cuentas-por-pagar/antiguedad'
    | '/customers/$id'
    | '/customers/new'
    | '/customers/validacion-sat'
    | '/deliveries/$id'
    | '/fleet/new'
    | '/invoices/new'
    | '/invoices/reconciliation'
    | '/quotes/new'
    | '/returns/$id'
    | '/returns/pending'
    | '/settings/company'
    | '/settings/operations'
    | '/suppliers/$id'
    | '/users/permissions'
    | '/portal/$'
    | '/portal/contracts'
    | '/portal/estado-cuenta'
    | '/portal/leaderboard'
    | '/portal/mis-reportes'
    | '/portal/rentals'
    | '/bookings/'
    | '/conciliacion-bancaria/'
    | '/contracts/'
    | '/crm/'
    | '/cuentas-por-pagar/'
    | '/customers/'
    | '/deliveries/'
    | '/fleet/'
    | '/invoices/'
    | '/quotes/'
    | '/returns/'
    | '/settings/'
    | '/suppliers/'
    | '/users/'
    | '/portal/'
    | '/contracts/$id/edit'
    | '/fleet/$id/edit'
    | '/invoices/$id/edit'
    | '/quotes/$id/edit'
    | '/portal/quotes/$id'
    | '/contracts/$id/'
    | '/fleet/$id/'
    | '/invoices/$id/'
    | '/quotes/$id/'
    | '/portal/invoices/'
    | '/portal/quotes/'
    | '/portal/invoices/$id/pago'
    | '/portal/invoices/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/accounts-payable'
    | '/activity'
    | '/audit'
    | '/availability'
    | '/bank-reconciliation'
    | '/calendar'
    | '/cash-flow'
    | '/changelog'
    | '/conciliacion'
    | '/cuentas-bancarias'
    | '/damage'
    | '/expenses'
    | '/feedback'
    | '/flujo-de-caja'
    | '/help'
    | '/income-statement'
    | '/inventory'
    | '/leaderboard'
    | '/login'
    | '/maintenance'
    | '/mis-reportes'
    | '/mrr'
    | '/payments'
    | '/prospects'
    | '/reports'
    | '/portal/login'
    | '/bookings/$id'
    | '/bookings/new'
    | '/conciliacion-bancaria/historial'
    | '/contracts/new'
    | '/crm/cerrados'
    | '/cuentas-por-pagar/antiguedad'
    | '/customers/$id'
    | '/customers/new'
    | '/customers/validacion-sat'
    | '/deliveries/$id'
    | '/fleet/new'
    | '/invoices/new'
    | '/invoices/reconciliation'
    | '/quotes/new'
    | '/returns/$id'
    | '/returns/pending'
    | '/settings/company'
    | '/settings/operations'
    | '/suppliers/$id'
    | '/users/permissions'
    | '/portal/$'
    | '/portal/contracts'
    | '/portal/estado-cuenta'
    | '/portal/leaderboard'
    | '/portal/mis-reportes'
    | '/portal/rentals'
    | '/bookings'
    | '/conciliacion-bancaria'
    | '/contracts'
    | '/crm'
    | '/cuentas-por-pagar'
    | '/customers'
    | '/deliveries'
    | '/fleet'
    | '/invoices'
    | '/quotes'
    | '/returns'
    | '/settings'
    | '/suppliers'
    | '/users'
    | '/portal'
    | '/contracts/$id/edit'
    | '/fleet/$id/edit'
    | '/invoices/$id/edit'
    | '/quotes/$id/edit'
    | '/portal/quotes/$id'
    | '/contracts/$id'
    | '/fleet/$id'
    | '/invoices/$id'
    | '/quotes/$id'
    | '/portal/invoices'
    | '/portal/quotes'
    | '/portal/invoices/$id/pago'
    | '/portal/invoices/$id'
  id:
    | '__root__'
    | '/_main'
    | '/_portal'
    | '/_main/$'
    | '/_main/accounts-payable'
    | '/_main/activity'
    | '/_main/audit'
    | '/_main/availability'
    | '/_main/bank-reconciliation'
    | '/_main/calendar'
    | '/_main/cash-flow'
    | '/_main/changelog'
    | '/_main/conciliacion'
    | '/_main/cuentas-bancarias'
    | '/_main/damage'
    | '/_main/expenses'
    | '/_main/feedback'
    | '/_main/flujo-de-caja'
    | '/_main/help'
    | '/_main/income-statement'
    | '/_main/inventory'
    | '/_main/leaderboard'
    | '/_main/login'
    | '/_main/maintenance'
    | '/_main/mis-reportes'
    | '/_main/mrr'
    | '/_main/payments'
    | '/_main/prospects'
    | '/_main/reports'
    | '/portal/login'
    | '/_main/'
    | '/_main/bookings/$id'
    | '/_main/bookings/new'
    | '/_main/conciliacion-bancaria/historial'
    | '/_main/contracts/new'
    | '/_main/crm/cerrados'
    | '/_main/cuentas-por-pagar/antiguedad'
    | '/_main/customers/$id'
    | '/_main/customers/new'
    | '/_main/customers/validacion-sat'
    | '/_main/deliveries/$id'
    | '/_main/fleet/new'
    | '/_main/invoices/new'
    | '/_main/invoices/reconciliation'
    | '/_main/quotes/new'
    | '/_main/returns/$id'
    | '/_main/returns/pending'
    | '/_main/settings/company'
    | '/_main/settings/operations'
    | '/_main/suppliers/$id'
    | '/_main/users/permissions'
    | '/_portal/portal/$'
    | '/_portal/portal/contracts'
    | '/_portal/portal/estado-cuenta'
    | '/_portal/portal/leaderboard'
    | '/_portal/portal/mis-reportes'
    | '/_portal/portal/rentals'
    | '/_main/bookings/'
    | '/_main/conciliacion-bancaria/'
    | '/_main/contracts/'
    | '/_main/crm/'
    | '/_main/cuentas-por-pagar/'
    | '/_main/customers/'
    | '/_main/deliveries/'
    | '/_main/fleet/'
    | '/_main/invoices/'
    | '/_main/quotes/'
    | '/_main/returns/'
    | '/_main/settings/'
    | '/_main/suppliers/'
    | '/_main/users/'
    | '/_portal/portal/'
    | '/_main/contracts/$id/edit'
    | '/_main/fleet/$id/edit'
    | '/_main/invoices/$id/edit'
    | '/_main/quotes/$id/edit'
    | '/_portal/portal/quotes/$id'
    | '/_main/contracts/$id/'
    | '/_main/fleet/$id/'
    | '/_main/invoices/$id/'
    | '/_main/quotes/$id/'
    | '/_portal/portal/invoices/'
    | '/_portal/portal/quotes/'
    | '/_portal/portal/invoices/$id/pago'
    | '/_portal/portal/invoices/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MainRoute: typeof MainRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  PortalLoginRoute: typeof PortalLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_main': {
      id: '/_main'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/': {
      id: '/_main/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MainIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/$': {
      id: '/_main/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof MainSplatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/accounts-payable': {
      id: '/_main/accounts-payable'
      path: '/accounts-payable'
      fullPath: '/accounts-payable'
      preLoaderRoute: typeof MainAccountsPayableRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/activity': {
      id: '/_main/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof MainActivityRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/audit': {
      id: '/_main/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof MainAuditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/availability': {
      id: '/_main/availability'
      path: '/availability'
      fullPath: '/availability'
      preLoaderRoute: typeof MainAvailabilityRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bank-reconciliation': {
      id: '/_main/bank-reconciliation'
      path: '/bank-reconciliation'
      fullPath: '/bank-reconciliation'
      preLoaderRoute: typeof MainBankReconciliationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/calendar': {
      id: '/_main/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof MainCalendarRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cash-flow': {
      id: '/_main/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof MainCashFlowRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/changelog': {
      id: '/_main/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof MainChangelogRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/conciliacion': {
      id: '/_main/conciliacion'
      path: '/conciliacion'
      fullPath: '/conciliacion'
      preLoaderRoute: typeof MainConciliacionRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cuentas-bancarias': {
      id: '/_main/cuentas-bancarias'
      path: '/cuentas-bancarias'
      fullPath: '/cuentas-bancarias'
      preLoaderRoute: typeof MainCuentasBancariasRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/damage': {
      id: '/_main/damage'
      path: '/damage'
      fullPath: '/damage'
      preLoaderRoute: typeof MainDamageRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/expenses': {
      id: '/_main/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof MainExpensesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/feedback': {
      id: '/_main/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof MainFeedbackRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/flujo-de-caja': {
      id: '/_main/flujo-de-caja'
      path: '/flujo-de-caja'
      fullPath: '/flujo-de-caja'
      preLoaderRoute: typeof MainFlujoDeCajaRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/help': {
      id: '/_main/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof MainHelpRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/income-statement': {
      id: '/_main/income-statement'
      path: '/income-statement'
      fullPath: '/income-statement'
      preLoaderRoute: typeof MainIncomeStatementRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/inventory': {
      id: '/_main/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof MainInventoryRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/leaderboard': {
      id: '/_main/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof MainLeaderboardRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/login': {
      id: '/_main/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof MainLoginRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/maintenance': {
      id: '/_main/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MainMaintenanceRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mis-reportes': {
      id: '/_main/mis-reportes'
      path: '/mis-reportes'
      fullPath: '/mis-reportes'
      preLoaderRoute: typeof MainMisReportesRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/mrr': {
      id: '/_main/mrr'
      path: '/mrr'
      fullPath: '/mrr'
      preLoaderRoute: typeof MainMrrRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/payments': {
      id: '/_main/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof MainPaymentsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/prospects': {
      id: '/_main/prospects'
      path: '/prospects'
      fullPath: '/prospects'
      preLoaderRoute: typeof MainProspectsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/reports': {
      id: '/_main/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof MainReportsRouteImport
      parentRoute: typeof MainRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/portal/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_main/bookings/': {
      id: '/_main/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof MainBookingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bookings/$id': {
      id: '/_main/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof MainBookingsIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/bookings/new': {
      id: '/_main/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof MainBookingsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/conciliacion-bancaria/': {
      id: '/_main/conciliacion-bancaria/'
      path: '/conciliacion-bancaria'
      fullPath: '/conciliacion-bancaria/'
      preLoaderRoute: typeof MainConciliacionBancariaIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/conciliacion-bancaria/historial': {
      id: '/_main/conciliacion-bancaria/historial'
      path: '/conciliacion-bancaria/historial'
      fullPath: '/conciliacion-bancaria/historial'
      preLoaderRoute: typeof MainConciliacionBancariaHistorialRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contracts/': {
      id: '/_main/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof MainContractsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contracts/new': {
      id: '/_main/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof MainContractsNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/crm/': {
      id: '/_main/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof MainCrmIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/crm/cerrados': {
      id: '/_main/crm/cerrados'
      path: '/crm/cerrados'
      fullPath: '/crm/cerrados'
      preLoaderRoute: typeof MainCrmCerradosRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cuentas-por-pagar/': {
      id: '/_main/cuentas-por-pagar/'
      path: '/cuentas-por-pagar'
      fullPath: '/cuentas-por-pagar/'
      preLoaderRoute: typeof MainCuentasPorPagarIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/cuentas-por-pagar/antiguedad': {
      id: '/_main/cuentas-por-pagar/antiguedad'
      path: '/cuentas-por-pagar/antiguedad'
      fullPath: '/cuentas-por-pagar/antiguedad'
      preLoaderRoute: typeof MainCuentasPorPagarAntiguedadRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/customers/': {
      id: '/_main/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof MainCustomersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/customers/$id': {
      id: '/_main/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof MainCustomersIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/customers/new': {
      id: '/_main/customers/new'
      path: '/customers/new'
      fullPath: '/customers/new'
      preLoaderRoute: typeof MainCustomersNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/customers/validacion-sat': {
      id: '/_main/customers/validacion-sat'
      path: '/customers/validacion-sat'
      fullPath: '/customers/validacion-sat'
      preLoaderRoute: typeof MainCustomersValidacionSatRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/deliveries/': {
      id: '/_main/deliveries/'
      path: '/deliveries'
      fullPath: '/deliveries/'
      preLoaderRoute: typeof MainDeliveriesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/deliveries/$id': {
      id: '/_main/deliveries/$id'
      path: '/deliveries/$id'
      fullPath: '/deliveries/$id'
      preLoaderRoute: typeof MainDeliveriesIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleet/': {
      id: '/_main/fleet/'
      path: '/fleet'
      fullPath: '/fleet/'
      preLoaderRoute: typeof MainFleetIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleet/new': {
      id: '/_main/fleet/new'
      path: '/fleet/new'
      fullPath: '/fleet/new'
      preLoaderRoute: typeof MainFleetNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/invoices/': {
      id: '/_main/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof MainInvoicesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/invoices/new': {
      id: '/_main/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof MainInvoicesNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/invoices/reconciliation': {
      id: '/_main/invoices/reconciliation'
      path: '/invoices/reconciliation'
      fullPath: '/invoices/reconciliation'
      preLoaderRoute: typeof MainInvoicesReconciliationRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/quotes/': {
      id: '/_main/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof MainQuotesIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/quotes/new': {
      id: '/_main/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof MainQuotesNewRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/returns/': {
      id: '/_main/returns/'
      path: '/returns'
      fullPath: '/returns/'
      preLoaderRoute: typeof MainReturnsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/returns/$id': {
      id: '/_main/returns/$id'
      path: '/returns/$id'
      fullPath: '/returns/$id'
      preLoaderRoute: typeof MainReturnsIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/returns/pending': {
      id: '/_main/returns/pending'
      path: '/returns/pending'
      fullPath: '/returns/pending'
      preLoaderRoute: typeof MainReturnsPendingRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/': {
      id: '/_main/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof MainSettingsIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/company': {
      id: '/_main/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof MainSettingsCompanyRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/settings/operations': {
      id: '/_main/settings/operations'
      path: '/settings/operations'
      fullPath: '/settings/operations'
      preLoaderRoute: typeof MainSettingsOperationsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/suppliers/': {
      id: '/_main/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof MainSuppliersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/suppliers/$id': {
      id: '/_main/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof MainSuppliersIdRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/users/': {
      id: '/_main/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof MainUsersIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/users/permissions': {
      id: '/_main/users/permissions'
      path: '/users/permissions'
      fullPath: '/users/permissions'
      preLoaderRoute: typeof MainUsersPermissionsRouteImport
      parentRoute: typeof MainRoute
    }
    '/_portal/portal/': {
      id: '/_portal/portal/'
      path: '/portal'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/$': {
      id: '/_portal/portal/$'
      path: '/portal/$'
      fullPath: '/portal/$'
      preLoaderRoute: typeof PortalPortalSplatRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/contracts': {
      id: '/_portal/portal/contracts'
      path: '/portal/contracts'
      fullPath: '/portal/contracts'
      preLoaderRoute: typeof PortalPortalContractsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/estado-cuenta': {
      id: '/_portal/portal/estado-cuenta'
      path: '/portal/estado-cuenta'
      fullPath: '/portal/estado-cuenta'
      preLoaderRoute: typeof PortalPortalEstadoCuentaRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/leaderboard': {
      id: '/_portal/portal/leaderboard'
      path: '/portal/leaderboard'
      fullPath: '/portal/leaderboard'
      preLoaderRoute: typeof PortalPortalLeaderboardRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/mis-reportes': {
      id: '/_portal/portal/mis-reportes'
      path: '/portal/mis-reportes'
      fullPath: '/portal/mis-reportes'
      preLoaderRoute: typeof PortalPortalMisReportesRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/rentals': {
      id: '/_portal/portal/rentals'
      path: '/portal/rentals'
      fullPath: '/portal/rentals'
      preLoaderRoute: typeof PortalPortalRentalsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_main/contracts/$id/': {
      id: '/_main/contracts/$id/'
      path: '/contracts/$id'
      fullPath: '/contracts/$id/'
      preLoaderRoute: typeof MainContractsIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/contracts/$id/edit': {
      id: '/_main/contracts/$id/edit'
      path: '/contracts/$id/edit'
      fullPath: '/contracts/$id/edit'
      preLoaderRoute: typeof MainContractsIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleet/$id/': {
      id: '/_main/fleet/$id/'
      path: '/fleet/$id'
      fullPath: '/fleet/$id/'
      preLoaderRoute: typeof MainFleetIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/fleet/$id/edit': {
      id: '/_main/fleet/$id/edit'
      path: '/fleet/$id/edit'
      fullPath: '/fleet/$id/edit'
      preLoaderRoute: typeof MainFleetIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/invoices/$id/': {
      id: '/_main/invoices/$id/'
      path: '/invoices/$id'
      fullPath: '/invoices/$id/'
      preLoaderRoute: typeof MainInvoicesIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/invoices/$id/edit': {
      id: '/_main/invoices/$id/edit'
      path: '/invoices/$id/edit'
      fullPath: '/invoices/$id/edit'
      preLoaderRoute: typeof MainInvoicesIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/quotes/$id/': {
      id: '/_main/quotes/$id/'
      path: '/quotes/$id'
      fullPath: '/quotes/$id/'
      preLoaderRoute: typeof MainQuotesIdIndexRouteImport
      parentRoute: typeof MainRoute
    }
    '/_main/quotes/$id/edit': {
      id: '/_main/quotes/$id/edit'
      path: '/quotes/$id/edit'
      fullPath: '/quotes/$id/edit'
      preLoaderRoute: typeof MainQuotesIdEditRouteImport
      parentRoute: typeof MainRoute
    }
    '/_portal/portal/invoices/': {
      id: '/_portal/portal/invoices/'
      path: '/portal/invoices'
      fullPath: '/portal/invoices/'
      preLoaderRoute: typeof PortalPortalInvoicesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/quotes/': {
      id: '/_portal/portal/quotes/'
      path: '/portal/quotes'
      fullPath: '/portal/quotes/'
      preLoaderRoute: typeof PortalPortalQuotesIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/quotes/$id': {
      id: '/_portal/portal/quotes/$id'
      path: '/portal/quotes/$id'
      fullPath: '/portal/quotes/$id'
      preLoaderRoute: typeof PortalPortalQuotesIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/invoices/$id/': {
      id: '/_portal/portal/invoices/$id/'
      path: '/portal/invoices/$id'
      fullPath: '/portal/invoices/$id/'
      preLoaderRoute: typeof PortalPortalInvoicesIdIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/portal/invoices/$id/pago': {
      id: '/_portal/portal/invoices/$id/pago'
      path: '/portal/invoices/$id/pago'
      fullPath: '/portal/invoices/$id/pago'
      preLoaderRoute: typeof PortalPortalInvoicesIdPagoRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface MainRouteChildren {
  MainSplatRoute: typeof MainSplatRoute
  MainAccountsPayableRoute: typeof MainAccountsPayableRoute
  MainActivityRoute: typeof MainActivityRoute
  MainAuditRoute: typeof MainAuditRoute
  MainAvailabilityRoute: typeof MainAvailabilityRoute
  MainBankReconciliationRoute: typeof MainBankReconciliationRoute
  MainCalendarRoute: typeof MainCalendarRoute
  MainCashFlowRoute: typeof MainCashFlowRoute
  MainChangelogRoute: typeof MainChangelogRoute
  MainConciliacionRoute: typeof MainConciliacionRoute
  MainCuentasBancariasRoute: typeof MainCuentasBancariasRoute
  MainDamageRoute: typeof MainDamageRoute
  MainExpensesRoute: typeof MainExpensesRoute
  MainFeedbackRoute: typeof MainFeedbackRoute
  MainFlujoDeCajaRoute: typeof MainFlujoDeCajaRoute
  MainHelpRoute: typeof MainHelpRoute
  MainIncomeStatementRoute: typeof MainIncomeStatementRoute
  MainInventoryRoute: typeof MainInventoryRoute
  MainLeaderboardRoute: typeof MainLeaderboardRoute
  MainLoginRoute: typeof MainLoginRoute
  MainMaintenanceRoute: typeof MainMaintenanceRoute
  MainMisReportesRoute: typeof MainMisReportesRoute
  MainMrrRoute: typeof MainMrrRoute
  MainPaymentsRoute: typeof MainPaymentsRoute
  MainProspectsRoute: typeof MainProspectsRoute
  MainReportsRoute: typeof MainReportsRoute
  MainIndexRoute: typeof MainIndexRoute
  MainBookingsIdRoute: typeof MainBookingsIdRoute
  MainBookingsNewRoute: typeof MainBookingsNewRoute
  MainConciliacionBancariaHistorialRoute: typeof MainConciliacionBancariaHistorialRoute
  MainContractsNewRoute: typeof MainContractsNewRoute
  MainCrmCerradosRoute: typeof MainCrmCerradosRoute
  MainCuentasPorPagarAntiguedadRoute: typeof MainCuentasPorPagarAntiguedadRoute
  MainCustomersIdRoute: typeof MainCustomersIdRoute
  MainCustomersNewRoute: typeof MainCustomersNewRoute
  MainCustomersValidacionSatRoute: typeof MainCustomersValidacionSatRoute
  MainDeliveriesIdRoute: typeof MainDeliveriesIdRoute
  MainFleetNewRoute: typeof MainFleetNewRoute
  MainInvoicesNewRoute: typeof MainInvoicesNewRoute
  MainInvoicesReconciliationRoute: typeof MainInvoicesReconciliationRoute
  MainQuotesNewRoute: typeof MainQuotesNewRoute
  MainReturnsIdRoute: typeof MainReturnsIdRoute
  MainReturnsPendingRoute: typeof MainReturnsPendingRoute
  MainSettingsCompanyRoute: typeof MainSettingsCompanyRoute
  MainSettingsOperationsRoute: typeof MainSettingsOperationsRoute
  MainSuppliersIdRoute: typeof MainSuppliersIdRoute
  MainUsersPermissionsRoute: typeof MainUsersPermissionsRoute
  MainBookingsIndexRoute: typeof MainBookingsIndexRoute
  MainConciliacionBancariaIndexRoute: typeof MainConciliacionBancariaIndexRoute
  MainContractsIndexRoute: typeof MainContractsIndexRoute
  MainCrmIndexRoute: typeof MainCrmIndexRoute
  MainCuentasPorPagarIndexRoute: typeof MainCuentasPorPagarIndexRoute
  MainCustomersIndexRoute: typeof MainCustomersIndexRoute
  MainDeliveriesIndexRoute: typeof MainDeliveriesIndexRoute
  MainFleetIndexRoute: typeof MainFleetIndexRoute
  MainInvoicesIndexRoute: typeof MainInvoicesIndexRoute
  MainQuotesIndexRoute: typeof MainQuotesIndexRoute
  MainReturnsIndexRoute: typeof MainReturnsIndexRoute
  MainSettingsIndexRoute: typeof MainSettingsIndexRoute
  MainSuppliersIndexRoute: typeof MainSuppliersIndexRoute
  MainUsersIndexRoute: typeof MainUsersIndexRoute
  MainContractsIdEditRoute: typeof MainContractsIdEditRoute
  MainFleetIdEditRoute: typeof MainFleetIdEditRoute
  MainInvoicesIdEditRoute: typeof MainInvoicesIdEditRoute
  MainQuotesIdEditRoute: typeof MainQuotesIdEditRoute
  MainContractsIdIndexRoute: typeof MainContractsIdIndexRoute
  MainFleetIdIndexRoute: typeof MainFleetIdIndexRoute
  MainInvoicesIdIndexRoute: typeof MainInvoicesIdIndexRoute
  MainQuotesIdIndexRoute: typeof MainQuotesIdIndexRoute
}

const MainRouteChildren: MainRouteChildren = {
  MainSplatRoute: MainSplatRoute,
  MainAccountsPayableRoute: MainAccountsPayableRoute,
  MainActivityRoute: MainActivityRoute,
  MainAuditRoute: MainAuditRoute,
  MainAvailabilityRoute: MainAvailabilityRoute,
  MainBankReconciliationRoute: MainBankReconciliationRoute,
  MainCalendarRoute: MainCalendarRoute,
  MainCashFlowRoute: MainCashFlowRoute,
  MainChangelogRoute: MainChangelogRoute,
  MainConciliacionRoute: MainConciliacionRoute,
  MainCuentasBancariasRoute: MainCuentasBancariasRoute,
  MainDamageRoute: MainDamageRoute,
  MainExpensesRoute: MainExpensesRoute,
  MainFeedbackRoute: MainFeedbackRoute,
  MainFlujoDeCajaRoute: MainFlujoDeCajaRoute,
  MainHelpRoute: MainHelpRoute,
  MainIncomeStatementRoute: MainIncomeStatementRoute,
  MainInventoryRoute: MainInventoryRoute,
  MainLeaderboardRoute: MainLeaderboardRoute,
  MainLoginRoute: MainLoginRoute,
  MainMaintenanceRoute: MainMaintenanceRoute,
  MainMisReportesRoute: MainMisReportesRoute,
  MainMrrRoute: MainMrrRoute,
  MainPaymentsRoute: MainPaymentsRoute,
  MainProspectsRoute: MainProspectsRoute,
  MainReportsRoute: MainReportsRoute,
  MainIndexRoute: MainIndexRoute,
  MainBookingsIdRoute: MainBookingsIdRoute,
  MainBookingsNewRoute: MainBookingsNewRoute,
  MainConciliacionBancariaHistorialRoute:
    MainConciliacionBancariaHistorialRoute,
  MainContractsNewRoute: MainContractsNewRoute,
  MainCrmCerradosRoute: MainCrmCerradosRoute,
  MainCuentasPorPagarAntiguedadRoute: MainCuentasPorPagarAntiguedadRoute,
  MainCustomersIdRoute: MainCustomersIdRoute,
  MainCustomersNewRoute: MainCustomersNewRoute,
  MainCustomersValidacionSatRoute: MainCustomersValidacionSatRoute,
  MainDeliveriesIdRoute: MainDeliveriesIdRoute,
  MainFleetNewRoute: MainFleetNewRoute,
  MainInvoicesNewRoute: MainInvoicesNewRoute,
  MainInvoicesReconciliationRoute: MainInvoicesReconciliationRoute,
  MainQuotesNewRoute: MainQuotesNewRoute,
  MainReturnsIdRoute: MainReturnsIdRoute,
  MainReturnsPendingRoute: MainReturnsPendingRoute,
  MainSettingsCompanyRoute: MainSettingsCompanyRoute,
  MainSettingsOperationsRoute: MainSettingsOperationsRoute,
  MainSuppliersIdRoute: MainSuppliersIdRoute,
  MainUsersPermissionsRoute: MainUsersPermissionsRoute,
  MainBookingsIndexRoute: MainBookingsIndexRoute,
  MainConciliacionBancariaIndexRoute: MainConciliacionBancariaIndexRoute,
  MainContractsIndexRoute: MainContractsIndexRoute,
  MainCrmIndexRoute: MainCrmIndexRoute,
  MainCuentasPorPagarIndexRoute: MainCuentasPorPagarIndexRoute,
  MainCustomersIndexRoute: MainCustomersIndexRoute,
  MainDeliveriesIndexRoute: MainDeliveriesIndexRoute,
  MainFleetIndexRoute: MainFleetIndexRoute,
  MainInvoicesIndexRoute: MainInvoicesIndexRoute,
  MainQuotesIndexRoute: MainQuotesIndexRoute,
  MainReturnsIndexRoute: MainReturnsIndexRoute,
  MainSettingsIndexRoute: MainSettingsIndexRoute,
  MainSuppliersIndexRoute: MainSuppliersIndexRoute,
  MainUsersIndexRoute: MainUsersIndexRoute,
  MainContractsIdEditRoute: MainContractsIdEditRoute,
  MainFleetIdEditRoute: MainFleetIdEditRoute,
  MainInvoicesIdEditRoute: MainInvoicesIdEditRoute,
  MainQuotesIdEditRoute: MainQuotesIdEditRoute,
  MainContractsIdIndexRoute: MainContractsIdIndexRoute,
  MainFleetIdIndexRoute: MainFleetIdIndexRoute,
  MainInvoicesIdIndexRoute: MainInvoicesIdIndexRoute,
  MainQuotesIdIndexRoute: MainQuotesIdIndexRoute,
}

const MainRouteWithChildren = MainRoute._addFileChildren(MainRouteChildren)

interface PortalRouteChildren {
  PortalPortalSplatRoute: typeof PortalPortalSplatRoute
  PortalPortalContractsRoute: typeof PortalPortalContractsRoute
  PortalPortalEstadoCuentaRoute: typeof PortalPortalEstadoCuentaRoute
  PortalPortalLeaderboardRoute: typeof PortalPortalLeaderboardRoute
  PortalPortalMisReportesRoute: typeof PortalPortalMisReportesRoute
  PortalPortalRentalsRoute: typeof PortalPortalRentalsRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
  PortalPortalQuotesIdRoute: typeof PortalPortalQuotesIdRoute
  PortalPortalInvoicesIndexRoute: typeof PortalPortalInvoicesIndexRoute
  PortalPortalQuotesIndexRoute: typeof PortalPortalQuotesIndexRoute
  PortalPortalInvoicesIdPagoRoute: typeof PortalPortalInvoicesIdPagoRoute
  PortalPortalInvoicesIdIndexRoute: typeof PortalPortalInvoicesIdIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalSplatRoute: PortalPortalSplatRoute,
  PortalPortalContractsRoute: PortalPortalContractsRoute,
  PortalPortalEstadoCuentaRoute: PortalPortalEstadoCuentaRoute,
  PortalPortalLeaderboardRoute: PortalPortalLeaderboardRoute,
  PortalPortalMisReportesRoute: PortalPortalMisReportesRoute,
  PortalPortalRentalsRoute: PortalPortalRentalsRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
  PortalPortalQuotesIdRoute: PortalPortalQuotesIdRoute,
  PortalPortalInvoicesIndexRoute: PortalPortalInvoicesIndexRoute,
  PortalPortalQuotesIndexRoute: PortalPortalQuotesIndexRoute,
  PortalPortalInvoicesIdPagoRoute: PortalPortalInvoicesIdPagoRoute,
  PortalPortalInvoicesIdIndexRoute: PortalPortalInvoicesIdIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MainRoute: MainRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  PortalLoginRoute: PortalLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
